// Copyright 2020 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// This controller acts as a gatekeeper to a quadrant. It can isolate all its
// (downstream) AXI ports, gate its clock, and assert its reset through a
// register file mapped on the narrow AXI port.

// Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

// AUTOMATICALLY GENERATED by occamygen.py; edit the script instead.

module ${name}_quad_ctrl
  import ${name}_pkg::*;
#(
  parameter type axi_quad_out_req_t = logic,
  parameter type axi_quad_out_rsp_t = logic,
  parameter type axi_quad_in_req_t  = logic,
  parameter type axi_quad_in_rsp_t  = logic
)(
  input  logic     clk_i,
  input  logic     rst_ni,
  input  logic     test_mode_i,
  input  chip_id_t chip_id_i,
  // External request into cluster i this cycle (bingo access wake)
  input  logic     [NrClustersPerQuad-1:0] bingo_cluster_access_i,
  // CSR Req/Rsp from cores
  // Here we assume each cluster has the same num of cores
  input  csr_req_t [NrClustersPerQuad-1:0][NrCoresPerCluster[0]-1:0] csr_req_i,
  input  logic     [NrClustersPerQuad-1:0][NrCoresPerCluster[0]-1:0] csr_req_valid_i,
  output logic     [NrClustersPerQuad-1:0][NrCoresPerCluster[0]-1:0] csr_req_ready_o,
  output csr_rsp_t [NrClustersPerQuad-1:0][NrCoresPerCluster[0]-1:0] csr_rsp_o,
  output logic     [NrClustersPerQuad-1:0][NrCoresPerCluster[0]-1:0] csr_rsp_valid_o,
  input  logic     [NrClustersPerQuad-1:0][NrCoresPerCluster[0]-1:0] csr_rsp_ready_i, 
  // Upward (SoC) narrow ports
  output ${soc_narrow_xbar.in_quad.req_type()} soc_out_req_o,
  input  ${soc_narrow_xbar.in_quad.rsp_type()} soc_out_rsp_i,
  input  ${soc_narrow_xbar.out_quad.req_type()} soc_in_req_i,
  output ${soc_narrow_xbar.out_quad.rsp_type()} soc_in_rsp_o,
  // Quadrant narrow ports
  output axi_quad_out_req_t quad_out_req_o,
  input  axi_quad_out_rsp_t quad_out_rsp_i,
  input  axi_quad_in_req_t  quad_in_req_i,
  output axi_quad_in_rsp_t  quad_in_rsp_o
);

  /// Bingo HW Manager Signals
  // We will use the CSR interface for the cores to read ready queue and write done queue
  // CSR Signals for the bingo hw manager
  // The +1 here is due to the host will also act as a core in cluster
  // For the TO case each cluster has two cores: gemm(core0) and dma(core1)
  // The host will be the core2 at cluster 0
  localparam int unsigned BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER = NrCoresPerCluster[0] + 1;
  localparam int unsigned CFG_WIDTH = 32;
  typedef logic [CFG_WIDTH-1:0] cfg_t;
  //  Task Desp
  logic [AddrWidth-1:0] bingo_hw_manager_task_list_base_addr;
  cfg_t bingo_hw_manager_num_task;
  cfg_t bingo_hw_manager_start;
  cfg_t bingo_hw_manager_reset_start;
  logic        bingo_hw_manager_reset_start_en;
  //  Power Management
  logic [AddrWidth-1:0] bingo_hw_manager_pm_base_addr;
  cfg_t bingo_hw_manager_enable_idle_pm;
  cfg_t bingo_hw_manager_idle_power_level;
  cfg_t bingo_hw_manager_boost_power_level;
  cfg_t bingo_hw_manager_idle_entry_delay;
  cfg_t bingo_hw_manager_access_wake_hold;
  cfg_t bingo_hw_manager_norm_power_level;
  cfg_t [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_core_power_domain;
  //  DVFS
  cfg_t                 bingo_hw_manager_pm_mode;
  logic [AddrWidth-1:0] bingo_hw_manager_dvfs_clint_msip_addr;
  cfg_t                 bingo_hw_manager_dvfs_ack;
  cfg_t                 bingo_hw_manager_dvfs_request;
  //  DARTS CERF
  logic        cerf_write_en;
  logic [31:0] cerf_write_data;
  logic [31:0] cerf_state;

  //  Bingo level-3 remote dispatch and status (see i_bingo_remote_link)
  // bingo_hw_manager_top TaskIdWidth (its default)
  localparam int unsigned BingoTaskIdWidth = 12;
  localparam int unsigned BingoRemoteSlotIdWidth =
    cf_math_pkg::idx_width(BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER * NrClustersPerQuad);
  localparam int unsigned BingoRemoteNumPeers = ${bingo_remote_num_peers};
  localparam logic [BingoRemoteNumPeers-1:0][${chip_id_width-1}:0] BingoRemotePeerChipId = {${bingo_remote_peer_chips}};
  // [core type] = {valid, target chip}
  localparam logic [2**${bingo_core_type_id_width}-1:0][${chip_id_width}:0] BingoRemoteTargetChip = {
    ${bingo_remote_target_chip}
  };
  // core types the link has a target for (the others are never exported)
  logic [2**${bingo_core_type_id_width}-1:0]                         bingo_rd_export_type_en;
  // one export queue per link peer: the peer of each core type, peers with a credit
  localparam int unsigned BingoRemotePeerIdWidth = (BingoRemoteNumPeers > 1) ? $clog2(BingoRemoteNumPeers) : 1;
  logic [2**${bingo_core_type_id_width}-1:0][BingoRemotePeerIdWidth-1:0] bingo_rd_export_type_peer;
  logic [BingoRemoteNumPeers-1:0]                                     bingo_rd_export_peer_ready;
  logic                                  bingo_rd_export_valid, bingo_rd_export_ready;
  logic [${quad_ctrl_axi_lite_xbar.dw-1}:0]                           bingo_rd_export_desc;
  logic [${bingo_core_type_id_width-1}:0]                            bingo_rd_export_core_type;
  chip_id_t                              bingo_rd_export_origin_chip;
  logic [BingoRemoteSlotIdWidth-1:0]     bingo_rd_export_proxy_slot;
  logic                                  bingo_rd_import_valid, bingo_rd_import_ready;
  logic [${quad_ctrl_axi_lite_xbar.dw-1}:0]                           bingo_rd_import_desc;
  logic [${bingo_core_type_id_width-1}:0]                            bingo_rd_import_core_type;
  chip_id_t                              bingo_rd_import_origin_chip;
  logic [BingoRemoteSlotIdWidth-1:0]     bingo_rd_import_proxy_slot;
  logic                                  bingo_rdn_out_valid, bingo_rdn_out_ready;
  chip_id_t                              bingo_rdn_out_chip;
  logic [BingoRemoteSlotIdWidth-1:0]     bingo_rdn_out_proxy_slot;
  logic [BingoTaskIdWidth-1:0]           bingo_rdn_out_task_id;
  logic                                  bingo_rdn_out_reject;
  logic                                  bingo_rdn_in_valid, bingo_rdn_in_ready;
  logic [BingoRemoteSlotIdWidth-1:0]     bingo_rdn_in_proxy_slot;
  logic [BingoTaskIdWidth-1:0]           bingo_rdn_in_task_id;
  logic                                  bingo_rdn_in_reject;
  logic [5:0]                            bingo_remote_link_error;
  logic                                  bingo_remote_done_mismatch;
  logic                                  bingo_remote_timeout;
  cfg_t                                  bingo_park_req, bingo_park_fail;
  // Fault precursors: late threshold, policy, epoch, clear, and at-risk slots
  cfg_t                                  bingo_risk_late, bingo_risk_policy, bingo_risk_epoch;
  cfg_t                                  bingo_risk_clear, bingo_risk;
  cfg_t                                  bingo_risk_confirm;
  // Boost choice: policy, credit per lost core, minimum load
  cfg_t                                  bingo_boost_policy;
  // CERF degradation table (index: core type) and the types that fired
  logic [${2**bingo_core_type_id_width-1}:0]       bingo_cerf_fb_en, bingo_cerf_fb_evt;
  logic [${2**bingo_core_type_id_width-1}:0][4:0]  bingo_cerf_fb_clear, bingo_cerf_fb_set;
  cfg_t                                  bingo_remote_proxy_timeout;
  logic                                  bingo_replay_stuck;
  logic [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_core_fenced;
  logic [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_replay_blocked;
  logic [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_core_dead_suspect;


  // Quadrant Lite xbar
  // Here we have the host to cluster mailboxes
  // There is 4kB space at the beginning of the quad cfg mux
  // The rest space is reserved fro the h2c mailbox
  addr_t [${num_clusters-1}:0] h2c_mailbox_base_addr;
  % for i in range(num_clusters):
  assign h2c_mailbox_base_addr[${i}] = (QuadAXILiteNarrowBaseAddr + 4096) + ${i} * H2CMailboxAddressSpace;
  % endfor


  ${module}

  // Connect SoC narrow ports
  // Quad to SoC -> SoC Out
  assign soc_out_req_o = ${quad_ctrl_quad_to_soc_xbar.out_soc_narrow.req_name()};
  assign ${quad_ctrl_quad_to_soc_xbar.out_soc_narrow.rsp_name()} = soc_out_rsp_i;
  // SoC in -> SoC to Quad
  assign ${quad_ctrl_soc_to_quad_xbar.in_soc_narrow.req_name()} = soc_in_req_i;
  assign soc_in_rsp_o = ${quad_ctrl_soc_to_quad_xbar.in_soc_narrow.rsp_name()};

  // Connect Quad narrow ports
  // SoC to Quad -> Quad Out
  assign quad_out_req_o = ${quad_ctrl_soc_to_quad_xbar.out_clusters.req_name()};
  assign ${quad_ctrl_soc_to_quad_xbar.out_clusters.rsp_name()} = quad_out_rsp_i;
  // Quad in -> Quad to SoC
  assign ${quad_ctrl_quad_to_soc_xbar.in_clusters.req_name()} = quad_in_req_i;
  assign quad_in_rsp_o = ${quad_ctrl_quad_to_soc_xbar.in_clusters.rsp_name()};

  // SoC to Quad Xbar -> Quad axi lite narrow
  <%
    quad_ctrl_soc_to_quad_xbar.out_quad_axi_lite_narrow \
      .atomic_adapter(context, filter=True, max_trans=4, name="soc_to_quad_axi_lite_narrow_noatop") \
      .change_dw(context, 32, "soc_to_quad_to_axi_lite_narrow_dw") \
      .to_axi_lite(context, name="soc_to_quad_to_axi_lite_narrow", to=quad_ctrl_axi_lite_narrow_mux.in_soc_to_quad)
  %>
  // SoC to Quad Xbar -> Quad axi lite
  <%
    quad_ctrl_soc_to_quad_xbar.out_quad_axi_lite \
      .atomic_adapter(context, filter=True, max_trans=4, name="soc_to_quad_axi_lite_noatop") \
      .to_axi_lite(context, name="soc_to_quad_to_axi_lite", to=quad_ctrl_axi_lite_xbar.in_soc_to_quad)
  %>

  // Quad to SoC Xbar -> Quad axi lite narrow
  <%
    quad_ctrl_quad_to_soc_xbar.out_quad_axi_lite_narrow \
      .atomic_adapter(context, filter=True, max_trans=4, name="quad_to_quad_axi_lite_narrow_noatop") \
      .change_dw(context, 32, "quad_to_soc_to_quad_axi_lite_narrow_dw") \
      .to_axi_lite(context, name="quad_to_soc_to_quad_axi_lite_narrow", to=quad_ctrl_axi_lite_narrow_mux.in_quad_to_soc)
  %>
  // Quad to SoC Xbar -> Quad axi lite 
  <%
    quad_ctrl_quad_to_soc_xbar.out_quad_axi_lite\
      .atomic_adapter(context, filter=True, max_trans=4, name="quad_to_quad_axi_lite_noatop") \
      .to_axi_lite(context, name="quad_to_soc_to_quad_axi_lite", to=quad_ctrl_axi_lite_xbar.in_quad_to_soc)
  %>

  // Quad AXI Lite Xbar -> Quad to SoC Xbar
  <%
    quad_ctrl_axi_lite_xbar.out_quad_to_soc.to_axi(context, name="quad_axi_lite_to_quad_to_soc_xbar", to=quad_ctrl_quad_to_soc_xbar.in_quad_axi_lite)
  %>


  //////////////////////////////////////
  //  32bit Quad Control Periph Regs  //
  //////////////////////////////////////
  <% regbus_quad_ctrl = quad_ctrl_axi_lite_narrow_mux.out_quad_ctrl_perpheral \
    .to_reg(context, "axi_lite_to_reg_quad_ctrl_peripheral") %>
  occamy_quad_periph #(
    .BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER (BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER),
    .BINGO_HW_MANAGER_NR_CLUSTER          (NrClustersPerQuad),
    .reg_req_t ( ${regbus_quad_ctrl.req_type()} ),
    .reg_rsp_t ( ${regbus_quad_ctrl.rsp_type()} )
  ) i_occamy_quad_periph_regs (
    .clk_i                                  (${regbus_quad_ctrl.clk}             ),
    .rst_ni                                 (${regbus_quad_ctrl.rst}             ),
    .reg_req_i                              (${regbus_quad_ctrl.req_name()}      ),
    .reg_rsp_o                              (${regbus_quad_ctrl.rsp_name()}      ),
    .bingo_hw_manager_task_list_base_addr_o (bingo_hw_manager_task_list_base_addr),
    .bingo_hw_manager_num_task_o            (bingo_hw_manager_num_task           ),
    .bingo_hw_manager_start_o               (bingo_hw_manager_start              ),
    .bingo_hw_manager_reset_start_i         (bingo_hw_manager_reset_start        ),
    .bingo_hw_manager_reset_start_en_i      (bingo_hw_manager_reset_start_en     ),
    .bingo_hw_manager_pm_base_addr_o        (bingo_hw_manager_pm_base_addr       ),
    .bingo_hw_manager_enable_idle_pm_o      (bingo_hw_manager_enable_idle_pm     ),
    .bingo_hw_manager_idle_power_level_o    (bingo_hw_manager_idle_power_level   ),
    .bingo_hw_manager_boost_power_level_o   (bingo_hw_manager_boost_power_level  ),
    .bingo_hw_manager_idle_entry_delay_o    (bingo_hw_manager_idle_entry_delay   ),
    .bingo_hw_manager_access_wake_hold_o    (bingo_hw_manager_access_wake_hold   ),
    .bingo_hw_manager_norm_power_level_o    (bingo_hw_manager_norm_power_level   ),
    .bingo_hw_manager_core_power_domain_o   (bingo_hw_manager_core_power_domain  ),
    // DVFS
    .bingo_hw_manager_pm_mode_o             (bingo_hw_manager_pm_mode            ),
    .bingo_hw_manager_dvfs_clint_msip_addr_o(bingo_hw_manager_dvfs_clint_msip_addr),
    .bingo_hw_manager_dvfs_ack_o            (bingo_hw_manager_dvfs_ack           ),
    .bingo_hw_manager_dvfs_request_i        (bingo_hw_manager_dvfs_request       ),
    // DARTS CERF
    .cerf_write_en_o                        (cerf_write_en                       ),
    .cerf_write_data_o                      (cerf_write_data                     ),
    .cerf_state_i                           (cerf_state                          ),
    // Bingo status (read-only): BINGO_STATUS, BINGO_CORE_DEAD_SUSPECT, BINGO_CORE_FENCED
    .bingo_hw_manager_replay_stuck_i          (bingo_replay_stuck                  ),
    .bingo_hw_manager_remote_done_mismatch_i  (bingo_remote_done_mismatch          ),
    .bingo_hw_manager_remote_timeout_i        (bingo_remote_timeout                ),
    .bingo_hw_manager_remote_proxy_timeout_o  (bingo_remote_proxy_timeout          ),
    .bingo_hw_manager_park_req_o              (bingo_park_req                      ),
    .bingo_hw_manager_park_fail_i             (bingo_park_fail                     ),
    .bingo_hw_manager_cerf_fb_en_o            (bingo_cerf_fb_en                    ),
    .bingo_hw_manager_cerf_fb_clear_o         (bingo_cerf_fb_clear                 ),
    .bingo_hw_manager_cerf_fb_set_o           (bingo_cerf_fb_set                   ),
    .bingo_hw_manager_cerf_fb_evt_i           (bingo_cerf_fb_evt                   ),
    .bingo_hw_manager_risk_late_o             (bingo_risk_late                     ),
    .bingo_hw_manager_risk_policy_o           (bingo_risk_policy                   ),
    .bingo_hw_manager_risk_epoch_o            (bingo_risk_epoch                    ),
    .bingo_hw_manager_risk_confirm_o          (bingo_risk_confirm                  ),
    .bingo_hw_manager_risk_clear_o            (bingo_risk_clear                    ),
    .bingo_hw_manager_risk_i                  (bingo_risk                          ),
    .bingo_hw_manager_boost_policy_o          (bingo_boost_policy                  ),
    .bingo_hw_manager_remote_link_error_i     (bingo_remote_link_error             ),
    .bingo_hw_manager_core_dead_suspect_i     (bingo_core_dead_suspect             ),
    .bingo_hw_manager_core_fenced_i           (bingo_core_fenced                   ),
    .bingo_hw_manager_replay_blocked_i        (bingo_replay_blocked                )
  );


  //////////////////////////////////////////////////////
  //  32bit Quad Contorl Periph Host2Cluster Mailbox  //
  //////////////////////////////////////////////////////
  % for i in range(num_clusters):
  <%
    axi_lite_h2c_mailbox_slave = quad_ctrl_axi_lite_narrow_mux.__dict__[f"out_h2c_mailbox_{i}"]
  %>
  // Mailbox ${i}
  hemaia_hw_mailbox #(
    .MailboxDepth(16),
    .IrqEdgeTrig (1'b0),
    .IrqActHigh  (1'b1),
    .AxiAddrWidth(${axi_lite_h2c_mailbox_slave.aw}),
    .AxiDataWidth(${axi_lite_h2c_mailbox_slave.dw}),
    .ChipIdWidth (${chip_id_width}),
    .req_lite_t  (${axi_lite_h2c_mailbox_slave.req_type()}),
    .resp_lite_t (${axi_lite_h2c_mailbox_slave.rsp_type()})
  ) i_h2c_mailbox_${i} (
    .clk_i (${axi_lite_h2c_mailbox_slave.clk}),
    .rst_ni(${axi_lite_h2c_mailbox_slave.rst}),
    .chip_id_i(chip_id_i),
    .test_i(1'b0),
    .req_i (${axi_lite_h2c_mailbox_slave.req_name()}),
    .resp_o(${axi_lite_h2c_mailbox_slave.rsp_name()}),
    .irq_o (),
    .base_addr_i(h2c_mailbox_base_addr[${i}])
  );
  % endfor

  ////////////////////////////////////////////////////
  //  64bit Quad AXI Lite Periph: Bingo HW Manager  //
  ////////////////////////////////////////////////////
  // ADDR Space for the axi lite periph
  localparam addr_t CHIPLET_DONE_QUEUE_BASE    = QuadAXILiteBaseAddr + 0 * 4096;
  localparam addr_t HOST_READY_DONE_QUEUE_BASE = QuadAXILiteBaseAddr + 1 * 4096;

  csr_req_t [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_csr_req;
  logic     [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_csr_req_valid;
  logic     [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_csr_req_ready;
  csr_rsp_t [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_csr_rsp;
  logic     [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_csr_rsp_valid;
  logic     [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_hw_manager_csr_rsp_ready;
  // The watchdog monitors the Snitch cores only: the extra slot (the host in
  // cluster 0, tied off in the other clusters) sends no heartbeats and is masked.
  localparam logic [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] BingoWatchdogCoreMask =
    {{NrClustersPerQuad{1'b0}}, {((BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1)*NrClustersPerQuad){1'b1}}};
  // Remap / replay: a fenced core's tasks may only run on a live core of the
  // same cluster with the same type. Generated from the cluster cfgs (occamygen
  // get_bingo_core_type_ids): cores with identical configs share a type, the
  // extra (host / tied-off) slot is 0.
<%
  nr_bingo_slots = num_cores_per_cluster + 1
  type_rows = []
  for core in reversed(range(nr_bingo_slots)):
    row = []
    for cluster in reversed(range(num_clusters)):
      ids = bingo_core_type_ids[cluster]
      row.append(f"{bingo_core_type_id_width}'d{ids[core] if core < len(ids) else 0}")
    type_rows.append((core, ", ".join(row)))
%>\
  localparam logic [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0][${bingo_core_type_id_width-1}:0] BingoCoreTypeId = {
% for core, row in type_rows:
    ${row}${"," if core != 0 else ""}  // core ${core}, clusters ${num_clusters-1}..0
% endfor
  };
  bingo_hw_manager_top #(
    .READY_AND_DONE_QUEUE_INTERFACE_TYPE(1), // 1: CSR 0: AXI LITE
    .TASK_QUEUE_TYPE                    (1), // 1: AXI Lite Master 0: Default AXI Lite Slave 
    .NUM_CORES_PER_CLUSTER    (BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER    ),
    .NUM_CLUSTERS_PER_CHIPLET (NrClustersPerQuad       ),
    // Per-edge dependency tag width (s1_quadrant.dep_tag_width). Must match the SW
    // descriptor packing: BINGO_DEP_TAG_WIDTH (occamy.h) / DEP_TAG_WIDTH (bingo_utils.h).
    .DepTagWidth              (${dep_tag_width}                          ),
    .TaskIdWidth              (BingoTaskIdWidth                          ),
    // DVFS doorbell MSIP bit: injected here so the PM is not hardcoded (see occamy.py
    // hw_manager_ipi_idx; must match HW_MANAGER_DVFS_MSIP_BIT / occamy_soc.sv ipi_i).
    .HOST_DVFS_MSIP_BIT       (${hw_manager_ipi_idx}                     ),
    // Watchdog: busy-core heartbeat timeout in quad-clock cycles
    // (s1_quadrant.bingo_watchdog_timeout_cycles, default 10_000_000). Healthy busy
    // cores write the heartbeat CSR periodically (sw/device/runtime/src/bingo_hw_heartbeat.h).
    .WatchdogHeartbeatTimeoutCycles ( ${bingo_watchdog_timeout_cycles}  ),
    // Fence (confirmed dead) timeout (s1_quadrant.bingo_watchdog_confirm_timeout_cycles,
    // default 0 = detection only). A fenced core's tasks are replayed on a live core of
    // the same type (BingoCoreTypeId); without one the manager only isolates it
    // (replay_stuck_o).
    .WatchdogConfirmTimeoutCycles ( ${bingo_watchdog_confirm_timeout_cycles} ),
    .WatchdogCoreMask         (BingoWatchdogCoreMask                     ),
    // Substitute levels (s1_quadrant.bingo_substitute_level_mask, default 1 =
    // same cluster only; bit 2 = remote chiplet through i_bingo_remote_link) and
    // the levels of an imported task's stand-in
    // (s1_quadrant.bingo_import_substitute_level_mask, default mask & 3)
    .SubstituteLevelMask       (3'd${bingo_substitute_level_mask}                   ),
    .ImportSubstituteLevelMask (3'd${bingo_import_substitute_level_mask}                   ),
    .RemoteNumPeers            (BingoRemoteNumPeers                                  ),
    .CoreTypeIdWidth          (${bingo_core_type_id_width}                                        ),
    .CoreTypeId               (BingoCoreTypeId                           ),
    // snax_intf_translator only forwards CSR 0x5fe/0x5ff to this port (0x5fd would
    // reach the accelerator CSRs), so the heartbeat is a write to the ready CSR.
    .CsrHeartbeatAddr         (csr_snax_def::CSR_SNAX_READ_TASK_READY_QUEUE),
    .HostAxiLiteAddrWidth     (${quad_ctrl_axi_lite_xbar.aw}             ),
    .HostAxiLiteDataWidth     (${quad_ctrl_axi_lite_xbar.dw}             ),
    .DeviceAxiLiteAddrWidth   (${quad_ctrl_axi_lite_narrow_mux.aw}       ),
    .DeviceAxiLiteDataWidth   (${quad_ctrl_axi_lite_narrow_mux.dw}       ),
    .host_axi_lite_req_t      (${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_chiplet_done_queue.req_type()}     ),
    .host_axi_lite_resp_t     (${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_chiplet_done_queue.rsp_type()}     ),
    .device_axi_lite_req_t    (${quad_ctrl_axi_lite_narrow_mux.out_quad_ctrl_perpheral.req_type()}              ),
    .device_axi_lite_resp_t   (${quad_ctrl_axi_lite_narrow_mux.out_quad_ctrl_perpheral.rsp_type()}               ),
    .csr_req_t                (csr_req_t                ),
    .csr_rsp_t                (csr_rsp_t                )
  ) i_bingo_hw_manager (
    .clk_i                              (clk_i                        ),
    .rst_ni                             (rst_ni                       ),
    .chip_id_i                          (chip_id_i                    ),
    // Since we set TASK_QUEUE_TYPE = 1
    // Not use the task queue slave
    .task_queue_base_addr_i             ('0                           ),
    .task_queue_axi_lite_req_i          ('0                           ),
    .task_queue_axi_lite_resp_o         (/* not used */               ),
    // We use the task queue master port 
    .task_list_base_addr_i              (bingo_hw_manager_task_list_base_addr       ),
    .num_task_i                         (bingo_hw_manager_num_task                  ),
    .bingo_hw_manager_start_i           (bingo_hw_manager_start                     ),
    .bingo_hw_manager_reset_start_o     (bingo_hw_manager_reset_start               ),
    .bingo_hw_manager_reset_start_en_o  (bingo_hw_manager_reset_start_en            ),
    .task_queue_axi_lite_req_o          (${quad_ctrl_axi_lite_xbar.in_bingo_hw_scheduler_read_local_task.req_name()}),
    .task_queue_axi_lite_resp_i         (${quad_ctrl_axi_lite_xbar.in_bingo_hw_scheduler_read_local_task.rsp_name()}),
    .chiplet_mailbox_base_addr_i        (CHIPLET_DONE_QUEUE_BASE                    ),
    .to_remote_chiplet_axi_lite_req_o   (${quad_ctrl_axi_lite_xbar.in_bingo_hw_scheduler_write_remote_done.req_name()}),
    .to_remote_chiplet_axi_lite_resp_i  (${quad_ctrl_axi_lite_xbar.in_bingo_hw_scheduler_write_remote_done.rsp_name()}),
    .from_remote_axi_lite_req_i         (${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_chiplet_done_queue.req_name()}),
    .from_remote_axi_lite_resp_o        (${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_chiplet_done_queue.rsp_name()}),
    // Since we set READY_AND_DONE_QUEUE_INTERFACE_TYPE=1
    // We do not use the axi lite slave for ready and done queue
    .done_queue_base_addr_i             ('0                           ),
    .done_queue_axi_lite_req_i          ('0                           ),
    .done_queue_axi_lite_resp_o         (/* not used */               ),
    .ready_queue_base_addr_i            ('0                           ),
    .ready_queue_axi_lite_req_i         ('0                           ),
    .ready_queue_axi_lite_resp_o        (/* not used */               ),
    .csr_req_i                          (bingo_hw_manager_csr_req                     ),
    .csr_req_valid_i                    (bingo_hw_manager_csr_req_valid               ),
    .csr_req_ready_o                    (bingo_hw_manager_csr_req_ready               ),
    .csr_rsp_o                          (bingo_hw_manager_csr_rsp                     ),
    .csr_rsp_valid_o                    (bingo_hw_manager_csr_rsp_valid               ),
    .csr_rsp_ready_i                    (bingo_hw_manager_csr_rsp_ready               ),
    // The Power Management interface
    .bingo_hw_manager_enable_idle_pm_i         (bingo_hw_manager_enable_idle_pm              ),
    .bingo_hw_manager_idle_power_level_i       (bingo_hw_manager_idle_power_level            ),
    .bingo_hw_manager_boost_power_level_i      (bingo_hw_manager_boost_power_level           ),
    .bingo_hw_manager_boost_policy_i           (bingo_boost_policy                           ),
    .bingo_hw_manager_idle_entry_delay_i       (bingo_hw_manager_idle_entry_delay            ),
    .bingo_hw_manager_park_req_i               (bingo_park_req                               ),
    .bingo_hw_manager_park_fail_o              (bingo_park_fail                              ),
    .bingo_hw_manager_risk_late_i              (bingo_risk_late                              ),
    .bingo_hw_manager_risk_policy_i            (bingo_risk_policy                            ),
    .bingo_hw_manager_risk_epoch_i             (bingo_risk_epoch                             ),
    .bingo_hw_manager_risk_confirm_i           (bingo_risk_confirm                           ),
    .bingo_hw_manager_risk_clear_i             (bingo_risk_clear                             ),
    .bingo_hw_manager_risk_o                   (bingo_risk                                   ),
    .bingo_hw_manager_cluster_access_i         (bingo_cluster_access_i                       ),
    .bingo_hw_manager_access_wake_hold_i       (bingo_hw_manager_access_wake_hold            ),
    .bingo_hw_manager_normal_power_level_i     (bingo_hw_manager_norm_power_level            ),
    .bingo_hw_manager_pm_base_addr_i           (bingo_hw_manager_pm_base_addr                ),
    .bingo_hw_manager_core_power_domain_i      (bingo_hw_manager_core_power_domain           ),
    // DVFS
    .bingo_hw_manager_pm_mode_i                (bingo_hw_manager_pm_mode                     ),
    .bingo_hw_manager_dvfs_clint_msip_addr_i   (bingo_hw_manager_dvfs_clint_msip_addr        ),
    .bingo_hw_manager_dvfs_ack_i               (bingo_hw_manager_dvfs_ack                    ),
    .bingo_hw_manager_dvfs_request_o           (bingo_hw_manager_dvfs_request                ),
    .pm_axi_lite_req_o                         (${quad_ctrl_axi_lite_xbar.in_bingo_hw_scheduler_write_pm.req_name()}),
    .pm_axi_lite_resp_i                        (${quad_ctrl_axi_lite_xbar.in_bingo_hw_scheduler_write_pm.rsp_name()}),
    // DARTS CERF
    .cerf_write_en_i                           (cerf_write_en                       ),
    .cerf_write_data_i                         (cerf_write_data                     ),
    .cerf_state_o                              (cerf_state                          ),
    .cerf_fb_en_i                              (bingo_cerf_fb_en                    ),
    .cerf_fb_clear_i                           (bingo_cerf_fb_clear                 ),
    .cerf_fb_set_i                             (bingo_cerf_fb_set                   ),
    .cerf_fb_evt_o                             (bingo_cerf_fb_evt                   ),
    // DARTS: Load Monitor (not connected yet)
    .load_total_pending_o                      (/* unused */                         ),
    // Watchdog / replay status (quad periph BINGO_* status registers)
    .core_fenced_o                             (bingo_core_fenced                    ),
    .core_dead_suspect_o                       (bingo_core_dead_suspect              ),
    .replay_stuck_o                            (bingo_replay_stuck                   ),
    .replay_blocked_o                          (bingo_replay_blocked                 ),
    // Level 3 remote dispatch (i_bingo_remote_link)
    .remote_dispatch_valid_o                   (bingo_rd_export_valid                ),
    .remote_dispatch_ready_i                   (bingo_rd_export_ready                ),
    .remote_dispatch_desc_o                    (bingo_rd_export_desc                 ),
    .remote_dispatch_core_type_o               (bingo_rd_export_core_type            ),
    .remote_dispatch_origin_chip_o             (bingo_rd_export_origin_chip          ),
    .remote_dispatch_proxy_slot_o              (bingo_rd_export_proxy_slot           ),
    .remote_dispatch_valid_i                   (bingo_rd_import_valid                ),
    .remote_dispatch_ready_o                   (bingo_rd_import_ready                ),
    .remote_dispatch_desc_i                    (bingo_rd_import_desc                 ),
    .remote_dispatch_core_type_i               (bingo_rd_import_core_type            ),
    .remote_dispatch_origin_chip_i             (bingo_rd_import_origin_chip          ),
    .remote_dispatch_proxy_slot_i              (bingo_rd_import_proxy_slot           ),
    .remote_done_valid_o                       (bingo_rdn_out_valid                  ),
    .remote_done_ready_i                       (bingo_rdn_out_ready                  ),
    .remote_done_chip_o                        (bingo_rdn_out_chip                   ),
    .remote_done_proxy_slot_o                  (bingo_rdn_out_proxy_slot             ),
    .remote_done_task_id_o                     (bingo_rdn_out_task_id                ),
    .remote_done_reject_o                      (bingo_rdn_out_reject                 ),
    .remote_done_valid_i                       (bingo_rdn_in_valid                   ),
    .remote_done_ready_o                       (bingo_rdn_in_ready                   ),
    .remote_done_proxy_slot_i                  (bingo_rdn_in_proxy_slot              ),
    .remote_done_task_id_i                     (bingo_rdn_in_task_id                 ),
    .remote_done_reject_i                      (bingo_rdn_in_reject                  ),
    .remote_export_type_en_i                   (bingo_rd_export_type_en              ),
    .remote_export_type_peer_i                 (bingo_rd_export_type_peer            ),
    .remote_export_peer_ready_i                (bingo_rd_export_peer_ready           ),
    .remote_proxy_timeout_i                    (bingo_remote_proxy_timeout           ),
    .remote_timeout_o                          (bingo_remote_timeout                 ),
    .remote_done_mismatch_o                    (bingo_remote_done_mismatch           )
  );

  //////////////////////////////////////////////////////////////////
  //  Bingo level-3 remote dispatch: bingo_hw_manager_remote_link  //
  //////////////////////////////////////////////////////////////////
  // Carries the exports / imports and dones of bingo_hw_manager_top as one
  // 64-bit AXI-Lite write per packet: master -> quad AXI-Lite xbar ->
  // {target chip, BingoRemoteDispatchMboxAddr / BingoRemoteDoneMboxAddr}. The
  // own chip id hits this quadrant's mailbox leaf (loopback), other chip ids
  // leave through quad_to_soc (default port). Off unless
  // s1_quadrant.bingo_substitute_level_mask[2] and a bingo_remote_target_chip
  // entry are set; otherwise nothing is exported and the link stays idle.
  bingo_hw_manager_remote_link #(
    .ChipIdWidth       ( ${chip_id_width}                    ),
    .CoreTypeIdWidth   ( ${bingo_core_type_id_width}                    ),
    .RemoteSlotIdWidth ( BingoRemoteSlotIdWidth     ),
    .TaskIdWidth       ( BingoTaskIdWidth           ),
    .AxiAddrWidth      ( ${quad_ctrl_axi_lite_xbar.aw}                   ),
    .AxiDataWidth      ( ${quad_ctrl_axi_lite_xbar.dw}                   ),
    .NumPeers          ( BingoRemoteNumPeers        ),
    .PeerChipId        ( BingoRemotePeerChipId      ),
    .RemoteTargetChip  ( BingoRemoteTargetChip      ),
    .DispatchCredits   ( ${bingo_remote_dispatch_credits}                    ),
    .req_t             ( ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_type()} ),
    .resp_t            ( ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.rsp_type()} )
  ) i_bingo_remote_link (
    .clk_i                 ( ${quad_ctrl_axi_lite_xbar.clk}                       ),
    .rst_ni                ( ${quad_ctrl_axi_lite_xbar.rst}                      ),
    .chip_id_i             ( chip_id_i                   ),
    .base_addr_i           ( BingoRemoteLinkBaseAddr     ),
    .export_valid_i        ( bingo_rd_export_valid       ),
    .export_ready_o        ( bingo_rd_export_ready       ),
    .export_desc_i         ( bingo_rd_export_desc        ),
    .export_core_type_i    ( bingo_rd_export_core_type   ),
    .export_origin_chip_i  ( bingo_rd_export_origin_chip ),
    .export_proxy_slot_i   ( bingo_rd_export_proxy_slot  ),
    .done_out_valid_i      ( bingo_rdn_out_valid         ),
    .done_out_ready_o      ( bingo_rdn_out_ready         ),
    .done_out_chip_i       ( bingo_rdn_out_chip          ),
    .done_out_proxy_slot_i ( bingo_rdn_out_proxy_slot    ),
    .done_out_task_id_i    ( bingo_rdn_out_task_id       ),
    .done_out_reject_i     ( bingo_rdn_out_reject        ),
    .import_valid_o        ( bingo_rd_import_valid       ),
    .import_ready_i        ( bingo_rd_import_ready       ),
    .import_desc_o         ( bingo_rd_import_desc        ),
    .import_core_type_o    ( bingo_rd_import_core_type   ),
    .import_origin_chip_o  ( bingo_rd_import_origin_chip ),
    .import_proxy_slot_o   ( bingo_rd_import_proxy_slot  ),
    .done_in_valid_o       ( bingo_rdn_in_valid          ),
    .done_in_ready_i       ( bingo_rdn_in_ready          ),
    .done_in_proxy_slot_o  ( bingo_rdn_in_proxy_slot     ),
    .done_in_task_id_o     ( bingo_rdn_in_task_id        ),
    .done_in_reject_o      ( bingo_rdn_in_reject         ),
    .mst_req_o             ( ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_name()} ),
    .mst_resp_i            ( ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.rsp_name()} ),
    .slv_req_i             ( ${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.req_name()} ),
    .slv_resp_o            ( ${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.rsp_name()} ),
    .target_valid_o        ( bingo_rd_export_type_en     ),
    .target_peer_o         ( bingo_rd_export_type_peer   ),
    .peer_ready_o          ( bingo_rd_export_peer_ready  ),
    .error_o               ( bingo_remote_link_error     ),
    .credits_o             ( /* unused */                )
  );

`ifndef SYNTHESIS
  // With degradation or late-beat monitoring enabled, log actual dispatches.
  // Check cleared branches and tasks routed away from an at-risk slot.
  cfg_t bingo_risk_clear_log_q;
  always @(posedge ${quad_ctrl_axi_lite_xbar.clk} or negedge ${quad_ctrl_axi_lite_xbar.rst}) begin
    if (!${quad_ctrl_axi_lite_xbar.rst}) bingo_risk_clear_log_q <= '0;
    else begin
      bingo_risk_clear_log_q <= bingo_risk_clear;
      if (bingo_risk_clear != bingo_risk_clear_log_q)
        $display("[BINGO_RISK_CLEAR] %0t mask=0x%0h", $time, bingo_risk_clear);
    end
  end
  logic dispatch_log_en;
  initial dispatch_log_en = $test$plusargs("bingo_dispatch_log");
  for (genvar core = 0; core < BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER; core++) begin : gen_bingo_dispatch_core_log
    for (genvar cluster = 0; cluster < NrClustersPerQuad; cluster++) begin : gen_bingo_dispatch_cluster_log
      always @(posedge ${quad_ctrl_axi_lite_xbar.clk}) begin
        if (${quad_ctrl_axi_lite_xbar.rst} && i_bingo_hw_manager.i_ctrl.risk_epoch_end &&
            (i_bingo_hw_manager.i_ctrl.risk_cnt_q[core][cluster] != 0) &&
            !i_bingo_hw_manager.risk_clear[core][cluster] &&
            !i_bingo_hw_manager.core_fenced[core][cluster] &&
            !i_bingo_hw_manager.wd_late[core][cluster])
          $display("[BINGO_RISK_DECAY] %0t core=%0d cluster=%0d count=%0d -> count=%0d",
                   $time, core, cluster, i_bingo_hw_manager.i_ctrl.risk_cnt_q[core][cluster],
                   i_bingo_hw_manager.i_ctrl.risk_cnt_q[core][cluster] >> 1);
        if (${quad_ctrl_axi_lite_xbar.rst} && ((|bingo_cerf_fb_en) || (|bingo_risk_late) || dispatch_log_en) &&
            i_bingo_hw_manager.ready_queue_pop[core][cluster])
          $display("[BINGO_DISPATCH] %0t chip=%0d task=%0d core=%0d cluster=%0d",
                   $time, chip_id_i, i_bingo_hw_manager.ready_queue_data_out[core][cluster].task_id,
                   core, cluster);
        if (${quad_ctrl_axi_lite_xbar.rst} && dispatch_log_en &&
            i_bingo_hw_manager.done_q_push[core][cluster])
          $display("[BINGO_DONE] %0t chip=%0d task=%0d core=%0d cluster=%0d",
                   $time, chip_id_i, i_bingo_hw_manager.done_q_data_in[core][cluster].task_id,
                   core, cluster);
      end
    end
  end
  // Simulation-only packet log of the remote link (address and 64-bit packet of
  // every AXI-Lite write it sends and receives, and the write responses).
  always @(posedge ${quad_ctrl_axi_lite_xbar.clk}) begin : bingo_remote_link_log
    if (${quad_ctrl_axi_lite_xbar.rst}) begin
      if (${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_name()}.aw_valid && ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.rsp_name()}.aw_ready)
        $display("[BINGO_RLINK_TX_AW] %0t chip=%0d addr=0x%012h", $time, chip_id_i, ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_name()}.aw.addr);
      if (${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_name()}.w_valid && ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.rsp_name()}.w_ready)
        $display("[BINGO_RLINK_TX_W] %0t chip=%0d data=0x%016h", $time, chip_id_i, ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_name()}.w.data);
      if (${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.rsp_name()}.b_valid && ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.req_name()}.b_ready)
        $display("[BINGO_RLINK_TX_B] %0t chip=%0d resp=%0d", $time, chip_id_i, ${quad_ctrl_axi_lite_xbar.in_bingo_remote_link.rsp_name()}.b.resp);
      if (${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.req_name()}.aw_valid && ${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.rsp_name()}.aw_ready)
        $display("[BINGO_RLINK_RX_AW] %0t chip=%0d addr=0x%012h", $time, chip_id_i, ${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.req_name()}.aw.addr);
      if (${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.req_name()}.w_valid && ${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.rsp_name()}.w_ready)
        $display("[BINGO_RLINK_RX_W] %0t chip=%0d data=0x%016h", $time, chip_id_i, ${quad_ctrl_axi_lite_xbar.out_bingo_remote_link.req_name()}.w.data);
    end
  end
  // The status that the quad periph BINGO_* registers show, on every change
  logic [8:0] bingo_status_log_q;
  logic [BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER-1:0][NrClustersPerQuad-1:0] bingo_fenced_log_q, bingo_suspect_log_q;
  always @(posedge ${quad_ctrl_axi_lite_xbar.clk} or negedge ${quad_ctrl_axi_lite_xbar.rst}) begin : bingo_status_log
    if (!${quad_ctrl_axi_lite_xbar.rst}) begin
      bingo_status_log_q  <= '0;
      bingo_fenced_log_q  <= '0;
      bingo_suspect_log_q <= '0;
    end else begin
      bingo_status_log_q  <= {bingo_remote_timeout, bingo_remote_link_error, bingo_remote_done_mismatch, bingo_replay_stuck};
      bingo_fenced_log_q  <= bingo_core_fenced;
      bingo_suspect_log_q <= bingo_core_dead_suspect;
      if (({bingo_remote_timeout, bingo_remote_link_error, bingo_remote_done_mismatch, bingo_replay_stuck} != bingo_status_log_q) ||
          (bingo_core_fenced != bingo_fenced_log_q) || (bingo_core_dead_suspect != bingo_suspect_log_q)) begin
        // fenced / dead_suspect in the order of the status registers: bit
        // core + cluster * BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER
        automatic logic [63:0] fenced_reg = '0, suspect_reg = '0;
        for (int core = 0; core < BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER; core++) begin
          for (int cluster = 0; cluster < NrClustersPerQuad; cluster++) begin
            fenced_reg[core + cluster*BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER]  = bingo_core_fenced[core][cluster];
            suspect_reg[core + cluster*BINGO_HW_MANAGER_NR_CORE_PER_CLUSTER] = bingo_core_dead_suspect[core][cluster];
          end
        end
        $display("[BINGO_STATUS] %0t chip=%0d replay_stuck=%0b remote_done_mismatch=%0b link_error=%0d fenced=0x%0h dead_suspect=0x%0h remote_timeout=%0b",
                 $time, chip_id_i, bingo_replay_stuck, bingo_remote_done_mismatch, bingo_remote_link_error,
                 fenced_reg, suspect_reg, bingo_remote_timeout);
      end
    end
  end
`endif

  // We need an extra work here to connect the host master port to the csr
  csr_req_t host_ready_done_csr_req;
  logic host_ready_done_csr_req_valid;
  logic host_ready_done_csr_req_ready;
  csr_rsp_t host_ready_done_csr_rsp;
  logic host_ready_done_csr_rsp_valid;
  logic host_ready_done_csr_rsp_ready;
  axi_lite_to_csr #(
    .AXI_LITE_ADDR_WIDTH(${quad_ctrl_axi_lite_xbar.aw}),
    .AXI_LITE_DATA_WIDTH(${quad_ctrl_axi_lite_xbar.dw}),
    .axi_lite_req_t(${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_host_ready_done_intf.req_type()}),
    .axi_lite_rsp_t(${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_host_ready_done_intf.rsp_type()}),
    .csr_req_t(csr_req_t),
    .csr_rsp_t(csr_rsp_t)
  ) i_host_ready_done_axi_lite_to_csr (
    .clk_i(${quad_ctrl_axi_lite_xbar.clk}),
    .rst_ni(${quad_ctrl_axi_lite_xbar.rst}),
    .axi_lite_req_i(${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_host_ready_done_intf.req_name()}),
    .axi_lite_rsp_o(${quad_ctrl_axi_lite_xbar.out_bingo_hw_scheduler_host_ready_done_intf.rsp_name()}),
    .csr_req_o      (host_ready_done_csr_req),
    .csr_req_valid_o(host_ready_done_csr_req_valid),
    .csr_req_ready_i(host_ready_done_csr_req_ready),
    .csr_rsp_i      (host_ready_done_csr_rsp),
    .csr_rsp_valid_i(host_ready_done_csr_rsp_valid),
    .csr_rsp_ready_o(host_ready_done_csr_rsp_ready)
  );
  // snax_intf_translator subtracts CSR_SNAX_BEGIN from the CSR number; restore the
  // architectural CSR number (0x5fe ready / 0x5ff done) that bingo_hw_manager decodes.
  %for cluster in range(num_clusters):
    %for core in range(num_cores_per_cluster):
    // Connect Normal Core${core} Cluster${cluster}
  assign bingo_hw_manager_csr_req[${core}][${cluster}].addr  = csr_req_i[${cluster}][${core}].addr + addr_t'(csr_snax_def::CSR_SNAX_BEGIN);// CSR request from the core
  assign bingo_hw_manager_csr_req[${core}][${cluster}].data  = csr_req_i[${cluster}][${core}].data;
  assign bingo_hw_manager_csr_req[${core}][${cluster}].write = csr_req_i[${cluster}][${core}].write;
  assign bingo_hw_manager_csr_req_valid[${core}][${cluster}] = csr_req_valid_i[${cluster}][${core}];
  assign csr_req_ready_o[${cluster}][${core}] = bingo_hw_manager_csr_req_ready[${core}][${cluster}];
  assign csr_rsp_o[${cluster}][${core}] = bingo_hw_manager_csr_rsp[${core}][${cluster}];
  assign csr_rsp_valid_o[${cluster}][${core}] = bingo_hw_manager_csr_rsp_valid[${core}][${cluster}];
  assign bingo_hw_manager_csr_rsp_ready[${core}][${cluster}] = csr_rsp_ready_i[${cluster}][${core}];
    %endfor
  %endfor

  // Special treat to host simd core
  %for cluster in range(num_clusters):
      %if cluster == 0:
  // Connect the host to cluster 0 ports. The host reads the ready queue and writes
  // the done queue at one MMIO word (axi_lite_to_csr forwards the raw MMIO address),
  // so map the access direction to the ready/done CSR numbers.
  assign bingo_hw_manager_csr_req[${num_cores_per_cluster}][${cluster}].addr  = host_ready_done_csr_req.write ?
                                                                               addr_t'(csr_snax_def::CSR_SNAX_WRITE_TASK_DONE_QUEUE) :
                                                                               addr_t'(csr_snax_def::CSR_SNAX_READ_TASK_READY_QUEUE);
  assign bingo_hw_manager_csr_req[${num_cores_per_cluster}][${cluster}].data  = host_ready_done_csr_req.data;
  assign bingo_hw_manager_csr_req[${num_cores_per_cluster}][${cluster}].write = host_ready_done_csr_req.write;
  assign bingo_hw_manager_csr_req_valid[${num_cores_per_cluster}][${cluster}] = host_ready_done_csr_req_valid;
  assign host_ready_done_csr_req_ready = bingo_hw_manager_csr_req_ready[${num_cores_per_cluster}][${cluster}];
  assign host_ready_done_csr_rsp = bingo_hw_manager_csr_rsp[${num_cores_per_cluster}][${cluster}];
  assign host_ready_done_csr_rsp_valid = bingo_hw_manager_csr_rsp_valid[${num_cores_per_cluster}][${cluster}];
  assign bingo_hw_manager_csr_rsp_ready[${num_cores_per_cluster}][${cluster}] = host_ready_done_csr_rsp_ready;
      %else:
  // Tie off Cluster ${cluster} unused ports
  assign bingo_hw_manager_csr_req[${num_cores_per_cluster}][${cluster}] = '0;
  assign bingo_hw_manager_csr_req_valid[${num_cores_per_cluster}][${cluster}] = '0;
  assign bingo_hw_manager_csr_rsp_ready[${num_cores_per_cluster}][${cluster}] = '0;
      %endif
  %endfor
endmodule
