// Copyright 2020 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Author: Florian Zaruba <zarubaf@iis.ee.ethz.ch>
// Author: Fabian Schuiki <fschuiki@iis.ee.ethz.ch>

// AUTOMATICALLY GENERATED by occamygen.py; edit the script instead.
<%
  #// Note: controller introduces *one* cut stage on both narrow bus directions
  cuts_narrx_with_cluster = 0
  cuts_widex_with_cluster = 0
  cuts_narrx_with_ctrl = 1
  cuts_widexpost_with_wideiwc_out = 1
  cuts_wideiwc_with_wideout = 1
  nr_clusters = len(occamy_cfg["clusters"])
  nr_cores_per_cluster = cluster_cfgs[0]["nr_cores"]
  noc_cfg = occamy_cfg["s1_quadrant"].get("noc_cfg",{})
  noc_name = noc_cfg.get("noc_name", {})
  en_floonoc = noc_cfg.get("en_floonoc", False)
  noc_array = noc_cfg.get("noc_array", {})
  x_num = noc_array[0] if noc_array else 1
  y_num = noc_array[1] if noc_array else 1
  wide_trans = int(occamy_cfg["s1_quadrant"]["wide_trans"])
  narrow_trans = int(occamy_cfg["s1_quadrant"]["narrow_trans"])
  ro_cache_cfg = occamy_cfg["s1_quadrant"].get("ro_cache_cfg", {})
  ro_cache_regions = ro_cache_cfg.get("address_regions", 1)
  narrow_tlb_cfg = occamy_cfg["s1_quadrant"].get("narrow_tlb_cfg", {})
  narrow_tlb_entries = narrow_tlb_cfg.get("l1_num_entries", 1)
  wide_tlb_cfg = occamy_cfg["s1_quadrant"].get("wide_tlb_cfg", {})
  wide_tlb_entries = wide_tlb_cfg.get("l1_num_entries", 1)
%>

`include "axi/typedef.svh"
`include "axi_tlb/typedef.svh"

module ${name}_quad
  import ${name}_pkg::*;
  %if en_floonoc:
  import floo_${noc_name}_noc_pkg::*;
  %endif
(
  input  logic                         clk_i,
  input  logic                         rst_ni,
  input  logic [${len(occamy_cfg["clusters"])-1}:0] clk_acc_i,
  input  logic [${len(occamy_cfg["clusters"])-1}:0] rst_acc_ni,
  input  logic                         test_mode_i,
  input  logic [31:0]                  boot_addr_i,
  input  chip_id_t                     chip_id_i,
  input  logic [NrCoresPerQuad-1:0] meip_i,
  input  logic [NrCoresPerQuad-1:0] mtip_i,
  input  logic [NrCoresPerQuad-1:0] msip_i,
  // Next-Level
  output ${soc_narrow_xbar.in_quad.req_type()} quadrant_narrow_out_req_o,
  input  ${soc_narrow_xbar.in_quad.rsp_type()} quadrant_narrow_out_rsp_i,
  input  ${soc_narrow_xbar.out_quad.req_type()} quadrant_narrow_in_req_i,
  output ${soc_narrow_xbar.out_quad.rsp_type()} quadrant_narrow_in_rsp_o,
  output ${soc_wide_xbar.in_quad.req_type()} quadrant_wide_out_req_o,
  input  ${soc_wide_xbar.in_quad.rsp_type()} quadrant_wide_out_rsp_i,
  input  ${soc_wide_xbar.out_quad.req_type()} quadrant_wide_in_req_i,
  output ${soc_wide_xbar.out_quad.rsp_type()} quadrant_wide_in_rsp_o,
  // SRAM configuration
  input  sram_cfg_quadrant_t sram_cfg_i
);

 // Calculate cluster base address based on `tile id`.
  addr_t cluster_base_offset;
  assign cluster_base_offset = {chip_id_i, ClusterBaseOffset[AddrWidth-ChipIdWidth-1:0]};

  addr_t [${nr_clusters-1}:0] cluster_base_addr;
  % for i in range(nr_clusters):
  assign cluster_base_addr[${i}] = cluster_base_offset + ${i} * ClusterAddressSpace;
  %endfor

  // Define types for IOTLBs
  `AXI_TLB_TYPEDEF_ALL(tlb, logic [AddrWidth-12-1:0], logic [AddrWidth-12-1:0])

  // Signals from Controller
  logic ro_enable, ro_flush_valid, ro_flush_ready;
  logic [${ro_cache_regions-1}:0][${soc_wide_xbar.in_quad.aw-1}:0] ro_start_addr, ro_end_addr;
  %if narrow_tlb_cfg:
  logic narrow_tlb_enable;
  tlb_entry_t [${narrow_tlb_entries-1}:0] narrow_tlb_entries;
  % endif
  %if wide_tlb_cfg:
  logic wide_tlb_enable;
  tlb_entry_t [${wide_tlb_entries-1}:0] wide_tlb_entries;
  % endif

  // Signals for CSR Req/Rsp to the QuadCtrl
  // Num_cluster * Num_core
  csr_req_t [${nr_clusters-1}:0][${nr_cores_per_cluster-1}:0] csr_req;
  logic     [${nr_clusters-1}:0][${nr_cores_per_cluster-1}:0] csr_req_valid;
  logic     [${nr_clusters-1}:0][${nr_cores_per_cluster-1}:0] csr_req_ready;
  csr_rsp_t [${nr_clusters-1}:0][${nr_cores_per_cluster-1}:0] csr_rsp;
  logic     [${nr_clusters-1}:0][${nr_cores_per_cluster-1}:0] csr_rsp_valid;
  logic     [${nr_clusters-1}:0][${nr_cores_per_cluster-1}:0] csr_rsp_ready;

  %for i in range(nr_clusters):
  // CSR Req/Rsp for Cluster ${i}
  csr_req_t [${nr_cores_per_cluster-1}:0] csr_req_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_req_valid_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_req_ready_${i};
  csr_rsp_t [${nr_cores_per_cluster-1}:0] csr_rsp_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_rsp_valid_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_rsp_ready_${i};
  // CSR Req/Rsp CDC
  csr_req_t [${nr_cores_per_cluster-1}:0] csr_req_cdc_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_req_cdc_valid_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_req_cdc_ready_${i};
  csr_rsp_t [${nr_cores_per_cluster-1}:0] csr_rsp_cdc_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_rsp_cdc_valid_${i};
  logic     [${nr_cores_per_cluster-1}:0] csr_rsp_cdc_ready_${i};
  // Assignment From Cluster to QuadCtrl
  %for j in range(nr_cores_per_cluster):
  // CSR Req/Rsp for Core ${j}
  assign csr_req[${i}][${j}] = csr_req_cdc_${i}[${j}];
  assign csr_req_valid[${i}][${j}] = csr_req_cdc_valid_${i}[${j}];
  assign csr_req_cdc_ready_${i}[${j}] = csr_req_ready[${i}][${j}];
  assign csr_rsp_${i}[${j}] = csr_rsp[${i}][${j}];
  assign csr_rsp_valid_${i}[${j}] = csr_rsp_valid[${i}][${j}];
  assign csr_rsp_ready[${i}][${j}] = csr_rsp_ready_${i}[${j}];
  %endfor
  %endfor

  ///////////////////////
  //   INTERCONNECTS   //
  ///////////////////////
%if en_floonoc:
  //////////////
  // FlooNoC  //
  //////////////

  ///Address Map of the 'floo_${noc_name}_noc' NoC.
  floo_${noc_name}_noc_pkg::sam_rule_t [${nr_clusters-1}:0] NoC_SAM;
  % for i in range(nr_clusters):
  <% 
    x = i // y_num + 1
    y = i % y_num
  %>
  assign NoC_SAM[${i}] = '{idx: '{x: ${x}, y: ${y}, port_id: 0}, start_addr: cluster_base_addr[${i}], end_addr:cluster_base_addr[${i}] + ClusterAddressSpace};
  %endfor

  ///Default ID
  floo_${noc_name}_noc_pkg::id_t DEFAULT_ID = '{x: 0, y: 0, port_id: 0};

  floo_${noc_name}_noc_pkg::axi_noc_narrow_out_req_t  [${x_num}:0][${y_num-1}:0] cluster_noc_narrow_out_req;
  floo_${noc_name}_noc_pkg::axi_noc_narrow_out_rsp_t  [${x_num}:0][${y_num-1}:0] cluster_noc_narrow_out_rsp;
  floo_${noc_name}_noc_pkg::axi_noc_wide_out_req_t    [${x_num}:0][${y_num-1}:0] cluster_noc_wide_out_req;
  floo_${noc_name}_noc_pkg::axi_noc_wide_out_rsp_t    [${x_num}:0][${y_num-1}:0] cluster_noc_wide_out_rsp;
  floo_${noc_name}_noc_pkg::axi_noc_narrow_in_req_t [${x_num}:0][${y_num-1}:0] cluster_noc_narrow_in_req;
  floo_${noc_name}_noc_pkg::axi_noc_narrow_in_rsp_t [${x_num}:0][${y_num-1}:0] cluster_noc_narrow_in_rsp;
  floo_${noc_name}_noc_pkg::axi_noc_wide_in_req_t   [${x_num}:0][${y_num-1}:0] cluster_noc_wide_in_req;
  floo_${noc_name}_noc_pkg::axi_noc_wide_in_rsp_t   [${x_num}:0][${y_num-1}:0] cluster_noc_wide_in_rsp;


  floo_${noc_name}_noc i_floonoc(
    .clk_i                       (clk_i                      ),
    .rst_ni                      (rst_ni             ),
    .test_enable_i               (test_mode_i                ),
    .Sam_i                       (NoC_SAM                    ),
    .en_default_idx_i            (1'b1                       ),
    .default_idx_i               (DEFAULT_ID                 ),
    .cluster_noc_narrow_in_req_i (cluster_noc_narrow_in_req  ),
    .cluster_noc_narrow_in_rsp_o (cluster_noc_narrow_in_rsp  ),
    .cluster_noc_wide_in_req_i   (cluster_noc_wide_in_req    ),
    .cluster_noc_wide_in_rsp_o   (cluster_noc_wide_in_rsp    ),
    .cluster_noc_narrow_out_req_o(cluster_noc_narrow_out_req ),
    .cluster_noc_narrow_out_rsp_i(cluster_noc_narrow_out_rsp ),
    .cluster_noc_wide_out_req_o  (cluster_noc_wide_out_req   ),
    .cluster_noc_wide_out_rsp_i  (cluster_noc_wide_out_rsp   )
  );
  // Tied the unused inputs
  % for j in range(1,y_num):
  assign cluster_noc_narrow_in_req[0][${j}] = '0;
  assign cluster_noc_wide_in_req[0][${j}] = '0;
  assign cluster_noc_narrow_out_rsp[0][${j}] = '0;
  assign cluster_noc_wide_out_rsp[0][${j}] = '0;
  % endfor

%else:
  ///////////////////
  //   CROSSBARS   //
  ///////////////////
  ${module}
%endif
  ///////////////////////////////
  // Narrow In + IW Converter //
  ///////////////////////////////
  %if en_floonoc:
  <%
    narrow_cluster_in_ctrl = soc_narrow_xbar.out_quad \
      .copy(name="narrow_cluster_in_ctrl") \
      .declare(context)
    narrow_cluster_in_ctrl \
      .cut(context, cuts_narrx_with_ctrl) \
      .change_iw(context, occamy_cfg["s1_quadrant"]["narrow_xbar_slv_id_width"], "narrow_cluster_in_iwc")
  %>
  assign cluster_noc_narrow_in_req[0][0] = narrow_cluster_in_iwc_req;
  assign narrow_cluster_in_iwc_rsp = cluster_noc_narrow_in_rsp[0][0];
  %else:
  <%
    narrow_cluster_in_ctrl = soc_narrow_xbar.out_quad \
      .copy(name="narrow_cluster_in_ctrl") \
      .declare(context)
    narrow_cluster_in_ctrl \
      .cut(context, cuts_narrx_with_ctrl) \
      .change_iw(context, quad_narrow_xbar.in_soc_to_quad.iw, "narrow_cluster_in_iwc", to=quad_narrow_xbar.in_soc_to_quad)
  %>
  %endif

  /////////////////////////////////////
  // Narrow Out + TLB + IW Converter //
  /////////////////////////////////////

  %if en_floonoc:
  // We do not have the solder for noc
  // So we do it manually for now

  floo_${noc_name}_noc_pkg::axi_noc_narrow_out_req_t narrow_cluster_out_tlb_req;
  floo_${noc_name}_noc_pkg::axi_noc_narrow_out_rsp_t narrow_cluster_out_tlb_rsp;

  %if narrow_tlb_cfg:
  axi_tlb_noreg #(
    .AxiSlvPortAddrWidth(48),
    .AxiMstPortAddrWidth(48),
    .AxiDataWidth(64),
    .AxiIdWidth(${occamy_cfg["s1_quadrant"]["narrow_xbar_slv_id_width"]}),
    .AxiUserWidth (${occamy_cfg["s1_quadrant"]["narrow_xbar_slv_user_width"]}),
    .AxiSlvPortMaxTxns(${occamy_cfg["s1_quadrant"]["narrow_tlb_cfg"]["max_trans"]}),
    .L1NumEntries(${occamy_cfg["s1_quadrant"]["narrow_tlb_cfg"]["l1_num_entries"]}),
    .L1CutAx(${"1'b1" if occamy_cfg["s1_quadrant"]["narrow_tlb_cfg"]["l1_cut_ax"] else "1'b0"}),
    .slv_req_t(floo_${noc_name}_noc_pkg::axi_noc_narrow_out_req_t),
    .mst_req_t(floo_${noc_name}_noc_pkg::axi_noc_narrow_out_req_t),
    .axi_resp_t(floo_${noc_name}_noc_pkg::axi_noc_narrow_out_rsp_t),
    .entry_t(tlb_entry_t)
  ) i_narrow_cluster_out_tlb (
    .clk_i (clk_quadrant),
    .rst_ni (rst_ni),
    .test_en_i(test_mode_i),
    .slv_req_i (cluster_noc_narrow_out_req[0][0]),
    .slv_resp_o (cluster_noc_narrow_out_rsp[0][0]),
    .mst_req_o (narrow_cluster_out_tlb_req),
    .mst_resp_i (narrow_cluster_out_tlb_rsp),
    .entries_i (narrow_tlb_entries),
    .bypass_i (~narrow_tlb_enable)
  );
  %else:
  assign narrow_cluster_out_tlb_req = cluster_noc_narrow_out_req[0][0];
  assign cluster_noc_narrow_out_rsp[0][0] = narrow_cluster_out_tlb_rsp;
  %endif
  <%
    quad_narrow_out_id_width = cluster_cfgs[0]["id_width_in"]
    quad_narrow_out_user_width = cluster_cfgs[0]["user_width"]
    #// We need to connect the cluster output to the quad ctrl first
    quad_ctrl_in_clusters_id_width = quad_ctrl_quad_to_soc_xbar.in_clusters.iw
    quad_ctrl_in_clusters_user_width = quad_ctrl_quad_to_soc_xbar.in_clusters.uw
    soc_narrow_out_id_width = soc_narrow_xbar.in_quad.iw
    soc_narrow_out_user_width = soc_narrow_xbar.in_quad.uw
  %>
  
  ${quad_ctrl_quad_to_soc_xbar.in_clusters.req_type()} narrow_cluster_out_iwc_req;
  ${quad_ctrl_quad_to_soc_xbar.in_clusters.rsp_type()} narrow_cluster_out_iwc_rsp;
  typedef logic [${quad_ctrl_in_clusters_id_width-quad_narrow_out_id_width-1}:0] narrow_cluster_out_iwc_pre_id_t;

  axi_id_prepend #(
    .slv_aw_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_aw_chan_t   ),
    .slv_w_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_w_chan_t    ),
    .slv_b_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_b_chan_t    ),
    .slv_ar_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_ar_chan_t   ),
    .slv_r_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_r_chan_t    ),
    .mst_aw_chan_t  ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.aw_chan_type()} ),
    .mst_w_chan_t   ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.w_chan_type()}  ),
    .mst_b_chan_t   ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.b_chan_type()}  ),
    .mst_ar_chan_t  ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.ar_chan_type()} ),
    .mst_r_chan_t   ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.r_chan_type()}  ),
    .NoBus          ( 1 ),
    .AxiIdWidthSlvPort ( ${quad_narrow_out_id_width} ),
    .AxiIdWidthMstPort ( ${quad_ctrl_in_clusters_id_width} )
  ) i_narrow_cluster_out_iwc (
    .pre_id_i           (narrow_cluster_out_iwc_pre_id_t'(0)),
    .slv_aw_chans_i     (narrow_cluster_out_tlb_req.aw),
    .slv_aw_valids_i    (narrow_cluster_out_tlb_req.aw_valid),
    .slv_aw_readies_o   (narrow_cluster_out_tlb_rsp.aw_ready),
    .slv_w_chans_i      (narrow_cluster_out_tlb_req.w),
    .slv_w_valids_i     (narrow_cluster_out_tlb_req.w_valid),
    .slv_w_readies_o    (narrow_cluster_out_tlb_rsp.w_ready),
    .slv_b_chans_o      (narrow_cluster_out_tlb_rsp.b),
    .slv_b_valids_o     (narrow_cluster_out_tlb_rsp.b_valid),
    .slv_b_readies_i    (narrow_cluster_out_tlb_req.b_ready),
    .slv_ar_chans_i     (narrow_cluster_out_tlb_req.ar),
    .slv_ar_valids_i    (narrow_cluster_out_tlb_req.ar_valid),
    .slv_ar_readies_o   (narrow_cluster_out_tlb_rsp.ar_ready),
    .slv_r_chans_o      (narrow_cluster_out_tlb_rsp.r),
    .slv_r_valids_o     (narrow_cluster_out_tlb_rsp.r_valid),
    .slv_r_readies_i    (narrow_cluster_out_tlb_req.r_ready),
    .mst_aw_chans_o     (narrow_cluster_out_iwc_req.aw),
    .mst_aw_valids_o    (narrow_cluster_out_iwc_req.aw_valid),
    .mst_aw_readies_i   (narrow_cluster_out_iwc_rsp.aw_ready),
    .mst_w_chans_o      (narrow_cluster_out_iwc_req.w),
    .mst_w_valids_o     (narrow_cluster_out_iwc_req.w_valid),
    .mst_w_readies_i    (narrow_cluster_out_iwc_rsp.w_ready),
    .mst_b_chans_i      (narrow_cluster_out_iwc_rsp.b),
    .mst_b_valids_i     (narrow_cluster_out_iwc_rsp.b_valid),
    .mst_b_readies_o    (narrow_cluster_out_iwc_req.b_ready),
    .mst_ar_chans_o     (narrow_cluster_out_iwc_req.ar),
    .mst_ar_valids_o    (narrow_cluster_out_iwc_req.ar_valid),
    .mst_ar_readies_i   (narrow_cluster_out_iwc_rsp.ar_ready),
    .mst_r_chans_i      (narrow_cluster_out_iwc_rsp.r),
    .mst_r_valids_i     (narrow_cluster_out_iwc_rsp.r_valid),
    .mst_r_readies_o    (narrow_cluster_out_iwc_req.r_ready)
  );

  ${quad_ctrl_quad_to_soc_xbar.in_clusters.req_type()} narrow_cluster_out_ctrl_req;
  ${quad_ctrl_quad_to_soc_xbar.in_clusters.rsp_type()} narrow_cluster_out_ctrl_rsp;
  axi_multicut #(
    .NoCuts     ( ${cuts_narrx_with_ctrl}),
    .aw_chan_t  ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.aw_chan_type()}),
    .w_chan_t   ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.w_chan_type()} ),
    .b_chan_t   ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.b_chan_type()} ),
    .ar_chan_t  ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.ar_chan_type()}),
    .r_chan_t   ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.r_chan_type()} ),
    .axi_req_t  ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.req_type()}    ),
    .axi_resp_t ( ${quad_ctrl_quad_to_soc_xbar.in_clusters.rsp_type()}    )
  ) i_narrow_cluster_out_ctrl (
    .clk_i      (clk_i),
    .rst_ni     (rst_ni),
    .slv_req_i  (narrow_cluster_out_iwc_req),
    .slv_resp_o (narrow_cluster_out_iwc_rsp),
    .mst_req_o  (narrow_cluster_out_ctrl_req),
    .mst_resp_i (narrow_cluster_out_ctrl_rsp)
  );  
  %else:
  <%
  #// Add TLB behind crossbar if enabled
  if narrow_tlb_cfg:
    narrow_cluster_out_tlb = quad_narrow_xbar.out_quad_to_soc \
    .add_tlb_no_reg(context, "narrow_cluster_out_tlb", \
      cfg=narrow_tlb_cfg, \
      entry_t="tlb_entry_t", \
      entries="narrow_tlb_entries", \
      bypass="~narrow_tlb_enable")
  else:
    narrow_cluster_out_tlb = quad_narrow_xbar.out_quad_to_soc
  #// Change ID width and cut
  narrow_cluster_out_ctrl = narrow_cluster_out_tlb \
    .change_iw(context, quad_ctrl_quad_to_soc_xbar.in_clusters.iw, "narrow_cluster_out_iwc") \
    .cut(context, cuts_narrx_with_ctrl, "narrow_cluster_out_ctrl")
  %>
  %endif
  /////////////////////////////////////////
  // Wide Out + RO Cache + IW Converter  //
  /////////////////////////////////////////
  %if en_floonoc:
  floo_${noc_name}_noc_pkg::axi_noc_wide_out_req_t quad_wide_out_tlb_req;
  floo_${noc_name}_noc_pkg::axi_noc_wide_out_rsp_t quad_wide_out_tlb_rsp;
  %if wide_tlb_cfg:
  axi_tlb_noreg #(
    .AxiSlvPortAddrWidth(48),
    .AxiMstPortAddrWidth(48),
    .AxiDataWidth(512),
    .AxiIdWidth(${occamy_cfg["s1_quadrant"]["wide_xbar_slv_id_width"]}),
    .AxiUserWidth (${occamy_cfg["s1_quadrant"]["wide_xbar_slv_user_width"]}),
    .AxiSlvPortMaxTxns(${occamy_cfg["s1_quadrant"]["wide_tlb_cfg"]["max_trans"]}),
    .L1NumEntries(${occamy_cfg["s1_quadrant"]["wide_tlb_cfg"]["l1_num_entries"]}),
    .L1CutAx(${"1'b1" if occamy_cfg["s1_quadrant"]["wide_tlb_cfg"]["l1_cut_ax"] else "1'b0"}),
    .slv_req_t(floo_${noc_name}_noc_pkg::axi_noc_wide_in_req_t),
    .mst_req_t(floo_${noc_name}_noc_pkg::axi_noc_wide_in_req_t),
    .axi_resp_t(floo_${noc_name}_noc_pkg::axi_noc_wide_in_rsp_t),
    .entry_t(tlb_entry_t)
  ) i_wide_cluster_out_tlb (
    .clk_i (clk_i),
    .rst_ni (rst_ni),
    .test_en_i(test_mode_i),
    .slv_req_i (cluster_noc_wide_out_req[0][0]),
    .slv_resp_o (cluster_noc_wide_out_rsp[0][0]),
    .mst_req_o (quad_wide_out_tlb_req),
    .mst_resp_i (quad_wide_out_tlb_rsp),
    .entries_i (wide_tlb_entries),
    .bypass_i (~wide_tlb_enable)
  );
  %else:

  assign quad_wide_out_tlb_req = cluster_noc_wide_out_req[0][0];
  assign cluster_noc_wide_out_rsp[0][0] = quad_wide_out_tlb_rsp;
  %endif

  <%
    ro_cache_id_width = 0
    if ro_cache_cfg:
      ro_cache_id_width = cluster_cfgs[0]["dma_id_width_in"] + 1
    else:
      ro_cache_id_width = cluster_cfgs[0]["dma_id_width_in"]
    ro_cache_user_width = cluster_cfgs[0]["dma_user_width"]
  %>

  ${soc_wide_xbar.in_quad.req_type()} wide_cluster_out_iwc_req;
  ${soc_wide_xbar.in_quad.rsp_type()} wide_cluster_out_iwc_rsp;
  typedef logic [${soc_wide_xbar.in_quad.iw-ro_cache_id_width-1}:0] wide_cluster_out_iwc_pre_id_t;

% if ro_cache_cfg:
  `AXI_TYPEDEF_ALL_CT(axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width},
                      axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_req_t,
                      axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_resp_t,
                      logic [47:0],
                      logic [${ro_cache_id_width-1}:0],
                      logic [511:0],
                      logic [63:0],
                      logic [${ro_cache_user_width-1}:0])

  axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_req_t snitch_ro_cache_req;
  axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_resp_t snitch_ro_cache_rsp;
  snitch_read_only_cache #(
      .LineWidth    (${occamy_cfg["s1_quadrant"]["ro_cache_cfg"]["width"]}),
      .LineCount    (${occamy_cfg["s1_quadrant"]["ro_cache_cfg"]["count"]}),
      .WayCount     (${occamy_cfg["s1_quadrant"]["ro_cache_cfg"]["sets"]}),
      .AxiAddrWidth (48),
      .AxiDataWidth (512),
      .AxiIdWidth   (${cluster_cfgs[0]["dma_id_width_in"]}),
      .AxiUserWidth (${cluster_cfgs[0]["dma_user_width"]}),
      .MaxTrans     (${occamy_cfg["s1_quadrant"]["ro_cache_cfg"]["max_trans"]}),
      .NrAddrRules  (${occamy_cfg["s1_quadrant"]["ro_cache_cfg"]["address_regions"]}),
      .slv_req_t    (floo_${noc_name}_noc_pkg::axi_noc_wide_out_req_t),
      .slv_rsp_t    (floo_${noc_name}_noc_pkg::axi_noc_wide_out_rsp_t),
      .mst_req_t    (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_req_t),
      .mst_rsp_t    (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_resp_t),
      .sram_cfg_data_t (sram_cfg_t),
      .sram_cfg_tag_t (sram_cfg_t)
    ) i_snitch_ro_cache (
      .clk_i (clk_i),
      .rst_ni (rst_ni),
      .enable_i (ro_enable),
      .flush_valid_i (ro_flush_valid),
      .flush_ready_o (ro_flush_ready),
      .start_addr_i (ro_start_addr),
      .end_addr_i (ro_end_addr),
      .axi_slv_req_i (quad_wide_out_tlb_req),
      .axi_slv_rsp_o (quad_wide_out_tlb_rsp),
      .axi_mst_req_o (snitch_ro_cache_req),
      .axi_mst_rsp_i (snitch_ro_cache_rsp),
      .sram_cfg_data_i (sram_cfg_i.rocache_data),
      .sram_cfg_tag_i (sram_cfg_i.rocache_tag)
    );

  axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_req_t snitch_ro_cache_cut_req;
  axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_resp_t snitch_ro_cache_cut_rsp;
  axi_multicut #(
    .NoCuts (1),
    .aw_chan_t  (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_aw_chan_t),
    .w_chan_t   (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_w_chan_t),
    .b_chan_t   (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_b_chan_t),
    .ar_chan_t  (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_ar_chan_t),
    .r_chan_t   (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_r_chan_t),
    .axi_req_t  (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_req_t),
    .axi_resp_t (axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_resp_t)
  ) i_snitch_ro_cache_cut (
    .clk_i (clk_i),
    .rst_ni (rst_ni),
    .slv_req_i (snitch_ro_cache_req),
    .slv_resp_o (snitch_ro_cache_rsp),
    .mst_req_o (snitch_ro_cache_cut_req),
    .mst_resp_i (snitch_ro_cache_cut_rsp)
  );

  axi_id_prepend #(
    .slv_aw_chan_t  ( axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_aw_chan_t ),
    .slv_w_chan_t   ( axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_w_chan_t ),
    .slv_b_chan_t   ( axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_b_chan_t ),
    .slv_ar_chan_t  ( axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_ar_chan_t ),
    .slv_r_chan_t   ( axi_a48_d512_i${ro_cache_id_width}_u${ro_cache_user_width}_r_chan_t ),
    .mst_aw_chan_t  ( ${soc_wide_xbar.in_quad.aw_chan_type()} ),
    .mst_w_chan_t   ( ${soc_wide_xbar.in_quad.w_chan_type()} ),
    .mst_b_chan_t   ( ${soc_wide_xbar.in_quad.b_chan_type()} ),
    .mst_ar_chan_t  ( ${soc_wide_xbar.in_quad.ar_chan_type()} ),
    .mst_r_chan_t   ( ${soc_wide_xbar.in_quad.r_chan_type()} ),
    .NoBus          ( 1 ),
    .AxiIdWidthSlvPort ( ${ro_cache_id_width} ),
    .AxiIdWidthMstPort ( ${soc_wide_xbar.in_quad.iw} )
  ) i_wide_cluster_out_iwc (
    .pre_id_i           (wide_cluster_out_iwc_pre_id_t'(0)),
    .slv_aw_chans_i     (snitch_ro_cache_cut_req.aw),
    .slv_aw_valids_i    (snitch_ro_cache_cut_req.aw_valid),
    .slv_aw_readies_o   (snitch_ro_cache_cut_rsp.aw_ready),
    .slv_w_chans_i      (snitch_ro_cache_cut_req.w),
    .slv_w_valids_i     (snitch_ro_cache_cut_req.w_valid),
    .slv_w_readies_o    (snitch_ro_cache_cut_rsp.w_ready),
    .slv_b_chans_o      (snitch_ro_cache_cut_rsp.b),
    .slv_b_valids_o     (snitch_ro_cache_cut_rsp.b_valid),
    .slv_b_readies_i    (snitch_ro_cache_cut_req.b_ready),
    .slv_ar_chans_i     (snitch_ro_cache_cut_req.ar),
    .slv_ar_valids_i    (snitch_ro_cache_cut_req.ar_valid),
    .slv_ar_readies_o   (snitch_ro_cache_cut_rsp.ar_ready),
    .slv_r_chans_o      (snitch_ro_cache_cut_rsp.r),
    .slv_r_valids_o     (snitch_ro_cache_cut_rsp.r_valid),
    .slv_r_readies_i    (snitch_ro_cache_cut_req.r_ready),
    .mst_aw_chans_o     (wide_cluster_out_iwc_req.aw),
    .mst_aw_valids_o    (wide_cluster_out_iwc_req.aw_valid),
    .mst_aw_readies_i   (wide_cluster_out_iwc_rsp.aw_ready),
    .mst_w_chans_o      (wide_cluster_out_iwc_req.w),
    .mst_w_valids_o     (wide_cluster_out_iwc_req.w_valid),
    .mst_w_readies_i    (wide_cluster_out_iwc_rsp.w_ready),
    .mst_b_chans_i      (wide_cluster_out_iwc_rsp.b),
    .mst_b_valids_i     (wide_cluster_out_iwc_rsp.b_valid),
    .mst_b_readies_o    (wide_cluster_out_iwc_req.b_ready),
    .mst_ar_chans_o     (wide_cluster_out_iwc_req.ar),
    .mst_ar_valids_o    (wide_cluster_out_iwc_req.ar_valid),
    .mst_ar_readies_i   (wide_cluster_out_iwc_rsp.ar_ready),
    .mst_r_chans_i      (wide_cluster_out_iwc_rsp.r),
    .mst_r_valids_i     (wide_cluster_out_iwc_rsp.r_valid),
    .mst_r_readies_o    (wide_cluster_out_iwc_req.r_ready)
  );
% else:
  axi_id_prepend #(
    .slv_aw_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_aw_chan_t ),
    .slv_w_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_w_chan_t ),
    .slv_b_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_b_chan_t ),
    .slv_ar_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_ar_chan_t ),
    .slv_r_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_r_chan_t ),
    .mst_aw_chan_t  ( ${soc_wide_xbar.in_quad.aw_chan_type()} ),
    .mst_w_chan_t   ( ${soc_wide_xbar.in_quad.w_chan_type()} ),
    .mst_b_chan_t   ( ${soc_wide_xbar.in_quad.b_chan_type()} ),
    .mst_ar_chan_t  ( ${soc_wide_xbar.in_quad.ar_chan_type()} ),
    .mst_r_chan_t   ( ${soc_wide_xbar.in_quad.r_chan_type()} ),
    .NoBus          ( 1 ),
    .AxiIdWidthSlvPort ( ${cluster_cfgs[0]["dma_id_width_in"]} ),
    .AxiIdWidthMstPort ( ${soc_wide_xbar.in_quad.iw} )
  ) i_wide_cluster_out_iwc (
    .pre_id_i           (wide_cluster_out_iwc_pre_id_t'(0)),
    .slv_aw_chans_i     (quad_wide_out_tlb_req.aw),
    .slv_aw_valids_i    (quad_wide_out_tlb_req.aw_valid),
    .slv_aw_readies_o   (quad_wide_out_tlb_rsp.aw_ready),
    .slv_w_chans_i      (quad_wide_out_tlb_req.w),
    .slv_w_valids_i     (quad_wide_out_tlb_req.w_valid),
    .slv_w_readies_o    (quad_wide_out_tlb_rsp.w_ready),
    .slv_b_chans_o      (quad_wide_out_tlb_rsp.b),
    .slv_b_valids_o     (quad_wide_out_tlb_rsp.b_valid),
    .slv_b_readies_i    (quad_wide_out_tlb_req.b_ready),
    .slv_ar_chans_i     (quad_wide_out_tlb_req.ar),
    .slv_ar_valids_i    (quad_wide_out_tlb_req.ar_valid),
    .slv_ar_readies_o   (quad_wide_out_tlb_rsp.ar_ready),
    .slv_r_chans_o      (quad_wide_out_tlb_rsp.r),
    .slv_r_valids_o     (quad_wide_out_tlb_rsp.r_valid),
    .slv_r_readies_i    (quad_wide_out_tlb_req.r_ready),
    .mst_aw_chans_o     (wide_cluster_out_iwc_req.aw),
    .mst_aw_valids_o    (wide_cluster_out_iwc_req.aw_valid),
    .mst_aw_readies_i   (wide_cluster_out_iwc_rsp.aw_ready),
    .mst_w_chans_o      (wide_cluster_out_iwc_req.w),
    .mst_w_valids_o     (wide_cluster_out_iwc_req.w_valid),
    .mst_w_readies_i    (wide_cluster_out_iwc_rsp.w_ready),
    .mst_b_chans_i      (wide_cluster_out_iwc_rsp.b),
    .mst_b_valids_i     (wide_cluster_out_iwc_rsp.b_valid),
    .mst_b_readies_o    (wide_cluster_out_iwc_req.b_ready),
    .mst_ar_chans_o     (wide_cluster_out_iwc_req.ar),
    .mst_ar_valids_o    (wide_cluster_out_iwc_req.ar_valid),
    .mst_ar_readies_i   (wide_cluster_out_iwc_rsp.ar_ready),
    .mst_r_chans_i      (wide_cluster_out_iwc_rsp.r),
    .mst_r_valids_i     (wide_cluster_out_iwc_rsp.r_valid),
    .mst_r_readies_o    (wide_cluster_out_iwc_req.r_ready)
  );
% endif

  ${soc_wide_xbar.in_quad.req_type()} wide_cluster_out_cut_req;
  ${soc_wide_xbar.in_quad.rsp_type()} wide_cluster_out_cut_rsp;

  axi_multicut #(
    .NoCuts (1),
    .aw_chan_t (${soc_wide_xbar.in_quad.aw_chan_type()}),
    .w_chan_t (${soc_wide_xbar.in_quad.w_chan_type()}),
    .b_chan_t (${soc_wide_xbar.in_quad.b_chan_type()}),
    .ar_chan_t (${soc_wide_xbar.in_quad.ar_chan_type()}),
    .r_chan_t (${soc_wide_xbar.in_quad.r_chan_type()}),
    .axi_req_t (${soc_wide_xbar.in_quad.req_type()}),
    .axi_resp_t (${soc_wide_xbar.in_quad.rsp_type()})
  ) i_wide_cluster_out_cut (
    .clk_i (clk_i),
    .rst_ni (rst_ni),
    .slv_req_i (wide_cluster_out_iwc_req),
    .slv_resp_o (wide_cluster_out_iwc_rsp),
    .mst_req_o (wide_cluster_out_cut_req),
    .mst_resp_i (wide_cluster_out_cut_rsp)
  );
  assign quadrant_wide_out_req_o = wide_cluster_out_cut_req;
  assign wide_cluster_out_cut_rsp = quadrant_wide_out_rsp_i;


  %else:
  <%
    wide_target_iw = occamy_cfg["s1_quadrant"]["wide_xbar_slv_id_width"]
    #// Add TLB behind crossbar if enabled
    if wide_tlb_cfg:
      wide_cluster_out_tlb = quad_wide_xbar.out_soc_wide \
      .add_tlb_no_reg(context, "wide_cluster_out_tlb", \
        cfg=wide_tlb_cfg, \
      entry_t="tlb_entry_t", \
      entries="wide_tlb_entries", \
      bypass="~wide_tlb_enable")
    else:
      wide_cluster_out_tlb = quad_wide_xbar.out_soc_wide
    #// Add RO cache behind TLB if enabled
    #// RO cache needs an extra ID bit
    wide_target_iw += 1
    if ro_cache_cfg:
      wide_cluster_out_ro_cache = wide_cluster_out_tlb \
      .add_ro_cache(context, "snitch_ro_cache", \
        ro_cache_cfg, \
        enable="ro_enable", \
        flush_valid="ro_flush_valid", \
        flush_ready="ro_flush_ready", \
        start_addr="ro_start_addr", \
        end_addr="ro_end_addr", \
        sram_cfg_data_t="sram_cfg_t", \
        sram_cfg_tag_t="sram_cfg_t", \
        sram_cfg_data_i="sram_cfg_i.rocache_data", \
        sram_cfg_tag_i="sram_cfg_i.rocache_tag")
    else:
      wide_cluster_out_ro_cache = wide_cluster_out_tlb
    #// Add another multicut as configured before IWC
    wide_cluster_out_ro_cache = wide_cluster_out_ro_cache.cut(context, cuts_widexpost_with_wideiwc_out)
    #// Change ID width and cut
    wide_cluster_out_cut = wide_cluster_out_ro_cache \
      .change_iw(context, wide_target_iw, "wide_cluster_out_iwc", max_txns_per_id=wide_trans) \
      .cut(context, cuts_wideiwc_with_wideout)
    #// Assert correct outgoing ID widths
    assert soc_wide_xbar.in_quad.iw == wide_cluster_out_cut.iw, f"Wide IW for S1 Quadrant and SoC mismatches. SOC IW={soc_wide_xbar.in_quad.iw}, Quadrant IW={wide_cluster_out_cut.iw}"
  %>

  assign quadrant_wide_out_req_o = ${wide_cluster_out_cut.req_name()};
  assign ${wide_cluster_out_cut.rsp_name()} = quadrant_wide_out_rsp_i;
  %endif
  ////////////////////////////
  // Wide In + IW Converter //
  ////////////////////////////
  %if en_floonoc:
  <%
    soc_wide_xbar.out_quad \
      .copy(name="wide_cluster_in") \
      .declare(context) \
      .cut(context, cuts_wideiwc_with_wideout) \
      .change_iw(context,  occamy_cfg["s1_quadrant"]["wide_xbar_slv_id_width"],"wide_cluster_in_iwc")
  %>
  // to SOC
  assign wide_cluster_in_req = quadrant_wide_in_req_i;
  assign quadrant_wide_in_rsp_o = wide_cluster_in_rsp;

  // to Quad NoC
  assign cluster_noc_wide_in_req[0][0] = wide_cluster_in_iwc_req;
  assign wide_cluster_in_iwc_rsp = cluster_noc_wide_in_rsp[0][0];
  %else:
  <%
    soc_wide_xbar.out_quad \
      .copy(name="wide_cluster_in_iwc") \
      .declare(context) \
      .cut(context, cuts_wideiwc_with_wideout) \
      .change_iw(context, quad_wide_xbar.in_soc_wide.iw, "wide_cluster_in_iwc", to=quad_wide_xbar.in_soc_wide)
  %>
  assign wide_cluster_in_iwc_req = quadrant_wide_in_req_i;
  assign quadrant_wide_in_rsp_o = wide_cluster_in_iwc_rsp;
  %endif


  // External requests into each cluster, before its input CDCs (quad clock):
  // the bingo control plane keeps an accessed cluster's power domain awake
  logic [${nr_clusters-1}:0] bingo_cluster_access;

  /////////////////////
  // Quad Controller //
  /////////////////////
  ${name}_quad_ctrl #(
    .axi_quad_out_req_t (${soc_narrow_xbar.out_quad.req_type()}),
    .axi_quad_out_rsp_t (${soc_narrow_xbar.out_quad.rsp_type()}),
    .axi_quad_in_req_t  (${quad_ctrl_quad_to_soc_xbar.in_clusters.req_type()}),
    .axi_quad_in_rsp_t  (${quad_ctrl_quad_to_soc_xbar.in_clusters.rsp_type()})
  ) i_${name}_quad_ctrl (
    .clk_i,
    .rst_ni,
    .test_mode_i,
    .chip_id_i,
    .bingo_cluster_access_i (bingo_cluster_access),
    .csr_req_i          (csr_req                    ),
    .csr_req_valid_i    (csr_req_valid              ),
    .csr_req_ready_o    (csr_req_ready              ),
    .csr_rsp_o          (csr_rsp                    ),
    .csr_rsp_valid_o    (csr_rsp_valid              ),
    .csr_rsp_ready_i    (csr_rsp_ready              ),
    .soc_out_req_o      (quadrant_narrow_out_req_o  ),
    .soc_out_rsp_i      (quadrant_narrow_out_rsp_i  ),
    .soc_in_req_i       (quadrant_narrow_in_req_i   ),
    .soc_in_rsp_o       (quadrant_narrow_in_rsp_o   ),
    %if en_floonoc:
    .quad_out_req_o     (narrow_cluster_in_ctrl_req ),
    .quad_out_rsp_i     (narrow_cluster_in_ctrl_rsp ),
    .quad_in_req_i      (narrow_cluster_out_ctrl_req),
    .quad_in_rsp_o      (narrow_cluster_out_ctrl_rsp)
    %else:    
    .quad_out_req_o     (${narrow_cluster_in_ctrl.req_name()}),
    .quad_out_rsp_i     (${narrow_cluster_in_ctrl.rsp_name()}),
    .quad_in_req_i      (${narrow_cluster_out_ctrl.req_name()}),
    .quad_in_rsp_o      (${narrow_cluster_out_ctrl.rsp_name()})
    %endif 
  );

% for i in range(nr_clusters):
  <%
    cluster_name = cluster_cfgs[i]["name"]
  %>
  ///////////////
  // Cluster ${i} //
  ///////////////
  logic [9:0] hart_base_id_${i};
  assign hart_base_id_${i} = HartIdOffset + NrCoresPerClusterOffset[${i}];
  %if en_floonoc:
  <% 
    x = i // y_num
    y = i % y_num
  %>

  // Cut for four AXI: Narrow In/Out, Wide In/Out

  // AXI CDC signals for narrow_in interface (quadrant_uncore -> accelerator)
  floo_${noc_name}_noc_pkg::axi_noc_narrow_out_req_t narrow_in_cdc_dst_req_${i};
  floo_${noc_name}_noc_pkg::axi_noc_narrow_out_rsp_t narrow_in_cdc_dst_rsp_${i};

  axi_cdc #(
    .aw_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_aw_chan_t ),
    .w_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_w_chan_t ),
    .b_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_b_chan_t ),
    .ar_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_ar_chan_t ),
    .r_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_r_chan_t ),
    .axi_req_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_req_t ),
    .axi_resp_t ( floo_${noc_name}_noc_pkg::axi_noc_narrow_out_rsp_t ),
    .LogDepth   ( 1 ),
    .SyncStages ( 2 )
  ) i_narrow_in_cdc_${i} (
    .src_clk_i  ( clk_i ),
    .src_rst_ni ( rst_ni ),
    .src_req_i  ( cluster_noc_narrow_out_req[${x+1}][${y}] ),
    .src_resp_o ( cluster_noc_narrow_out_rsp[${x+1}][${y}] ),
    .dst_clk_i  ( clk_acc_i[${i}] ),
    .dst_rst_ni ( rst_acc_ni[${i}] ),
    .dst_req_o  ( narrow_in_cdc_dst_req_${i} ),
    .dst_resp_i ( narrow_in_cdc_dst_rsp_${i} )
  );

  // AXI CDC signals for narrow_out interface (accelerator -> quadrant_uncore)
  floo_${noc_name}_noc_pkg::axi_noc_narrow_in_req_t narrow_out_cdc_src_req_${i};
  floo_${noc_name}_noc_pkg::axi_noc_narrow_in_rsp_t narrow_out_cdc_src_rsp_${i};

  axi_cdc #(
    .aw_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_aw_chan_t ),
    .w_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_w_chan_t ),
    .b_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_b_chan_t ),
    .ar_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_ar_chan_t ),
    .r_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_r_chan_t ),
    .axi_req_t  ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_req_t ),
    .axi_resp_t ( floo_${noc_name}_noc_pkg::axi_noc_narrow_in_rsp_t ),
    .LogDepth   ( 1 ),
    .SyncStages ( 2 )
  ) i_narrow_out_cdc_${i} (
    .src_clk_i  ( clk_acc_i[${i}] ),
    .src_rst_ni ( rst_acc_ni[${i}] ),
    .src_req_i  ( narrow_out_cdc_src_req_${i} ),
    .src_resp_o ( narrow_out_cdc_src_rsp_${i} ),
    .dst_clk_i  ( clk_i ),
    .dst_rst_ni ( rst_ni ),
    .dst_req_o  ( cluster_noc_narrow_in_req[${x+1}][${y}] ),
    .dst_resp_i ( cluster_noc_narrow_in_rsp[${x+1}][${y}] )
  );

  // AXI CDC signals for wide_in interface (quadrant_uncore -> accelerator)
  floo_${noc_name}_noc_pkg::axi_noc_wide_out_req_t wide_in_cdc_dst_req_${i};
  floo_${noc_name}_noc_pkg::axi_noc_wide_out_rsp_t wide_in_cdc_dst_rsp_${i};

  axi_cdc #(
    .aw_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_aw_chan_t ),
    .w_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_w_chan_t ),
    .b_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_b_chan_t ),
    .ar_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_ar_chan_t ),
    .r_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_r_chan_t ),
    .axi_req_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_req_t ),
    .axi_resp_t ( floo_${noc_name}_noc_pkg::axi_noc_wide_out_rsp_t ),
    .LogDepth   ( 1 ),
    .SyncStages ( 2 )
  ) i_wide_in_cdc_${i} (
    .src_clk_i  ( clk_i ),
    .src_rst_ni ( rst_ni ),
    .src_req_i  ( cluster_noc_wide_out_req[${x+1}][${y}] ),
    .src_resp_o ( cluster_noc_wide_out_rsp[${x+1}][${y}] ),
    .dst_clk_i  ( clk_acc_i[${i}] ),
    .dst_rst_ni ( rst_acc_ni[${i}] ),
    .dst_req_o  ( wide_in_cdc_dst_req_${i} ),
    .dst_resp_i ( wide_in_cdc_dst_rsp_${i} )
  );

  assign bingo_cluster_access[${i}] = cluster_noc_narrow_out_req[${x+1}][${y}].ar_valid |
                                      cluster_noc_narrow_out_req[${x+1}][${y}].aw_valid |
                                      cluster_noc_wide_out_req[${x+1}][${y}].ar_valid   |
                                      cluster_noc_wide_out_req[${x+1}][${y}].aw_valid;

  // AXI CDC signals for wide_out interface (accelerator -> quadrant_uncore)
  floo_${noc_name}_noc_pkg::axi_noc_wide_in_req_t wide_out_cdc_src_req_${i};
  floo_${noc_name}_noc_pkg::axi_noc_wide_in_rsp_t wide_out_cdc_src_rsp_${i};

  axi_cdc #(
    .aw_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_aw_chan_t ),
    .w_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_w_chan_t ),
    .b_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_b_chan_t ),
    .ar_chan_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_ar_chan_t ),
    .r_chan_t   ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_r_chan_t ),
    .axi_req_t  ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_req_t ),
    .axi_resp_t ( floo_${noc_name}_noc_pkg::axi_noc_wide_in_rsp_t ),
    .LogDepth   ( 1 ),
    .SyncStages ( 2 )
  ) i_wide_out_cdc_${i} (
    .src_clk_i  ( clk_acc_i[${i}] ),
    .src_rst_ni ( rst_acc_ni[${i}] ),
    .src_req_i  ( wide_out_cdc_src_req_${i} ),
    .src_resp_o ( wide_out_cdc_src_rsp_${i} ),
    .dst_clk_i  ( clk_i ),
    .dst_rst_ni ( rst_ni ),
    .dst_req_o  ( cluster_noc_wide_in_req[${x+1}][${y}] ),
    .dst_resp_i ( cluster_noc_wide_in_rsp[${x+1}][${y}] )
  );

  ${cluster_name}_wrapper i_${name}_cluster_${i} (
    .clk_i               (clk_acc_i[${i}]),
    .rst_ni              (rst_acc_ni[${i}]),
    .obs_o               (/* Not Connected */),
    .meip_i              (meip_i[NrCoresPerClusterOffset[${i}]+:NrCoresPerCluster[${i}]]),
    .mtip_i              (mtip_i[NrCoresPerClusterOffset[${i}]+:NrCoresPerCluster[${i}]]),
    .msip_i              (msip_i[NrCoresPerClusterOffset[${i}]+:NrCoresPerCluster[${i}]]),
    .hart_base_id_i      (hart_base_id_${i}),
    .cluster_base_addr_i (cluster_base_addr[${i}]),
    .boot_addr_i         (boot_addr_i),
    .csr_req_o           (csr_req_${i}               ),
    .csr_req_valid_o     (csr_req_valid_${i}         ),
    .csr_req_ready_i     (csr_req_ready_${i}         ),
    .csr_resp_i          (csr_rsp_cdc_${i}           ),
    .csr_resp_valid_i    (csr_rsp_cdc_valid_${i}     ),
    .csr_resp_ready_o    (csr_rsp_cdc_ready_${i}     ),
    .narrow_in_req_i     (narrow_in_cdc_dst_req_${i} ),
    .narrow_in_resp_o    (narrow_in_cdc_dst_rsp_${i} ),
    .narrow_out_req_o    (narrow_out_cdc_src_req_${i}),
    .narrow_out_resp_i   (narrow_out_cdc_src_rsp_${i}),
    .wide_out_req_o      (wide_out_cdc_src_req_${i}  ),
    .wide_out_resp_i     (wide_out_cdc_src_rsp_${i}  ),
    .wide_in_req_i       (wide_in_cdc_dst_req_${i}   ),
    .wide_in_resp_o      (wide_in_cdc_dst_rsp_${i}   ),
    .sram_cfgs_i         (sram_cfg_i.cluster         )
  );
  %else:

  <%
    narrow_cluster_in = quad_narrow_xbar.__dict__["out_cluster_{}".format(i)].change_iw(context, cluster_cfgs[i]["id_width_in"], "narrow_in_iwc_{}".format(i)).cut(context, cuts_narrx_with_cluster).cdc(context, target_clk="clk_acc_i[{}]".format(i), target_rst="rst_acc_ni[{}]".format(i), name="narrow_cluster_in_cdc_{}".format(i))

    narrow_cluster_out = quad_narrow_xbar.__dict__["in_cluster_{}".format(i)].copy(name="narrow_out_{}".format(i),clk="clk_acc_i[{}]".format(i),rst="rst_acc_ni[{}]".format(i)).declare(context)
    narrow_cluster_out.cdc(context, target_clk="clk_i", target_rst="rst_ni", name="narrow_cluster_out_cdc_{}".format(i)).cut(context, cuts_narrx_with_cluster, to=quad_narrow_xbar.__dict__["in_cluster_{}".format(i)])

    wide_cluster_in = quad_wide_xbar.__dict__["out_cluster_{}".format(i)].change_iw(context, cluster_cfgs[i]["dma_id_width_in"], "wide_in_iwc_{}".format(i), max_txns_per_id=wide_trans).cut(context, cuts_widex_with_cluster).cdc(context, target_clk="clk_acc_i[{}]".format(i), target_rst="rst_acc_ni[{}]".format(i), name="wide_cluster_in_cdc_{}".format(i))

    wide_cluster_out = quad_wide_xbar.__dict__["in_cluster_{}".format(i)].copy(name="wide_out_{}".format(i),clk="clk_acc_i[{}]".format(i),rst="rst_acc_ni[{}]".format(i)).declare(context)
    wide_cluster_out.cdc(context, target_clk="clk_i", target_rst="rst_ni", name="wide_cluster_out_cdc_{}".format(i)).cut(context, cuts_widex_with_cluster, to=quad_wide_xbar.__dict__["in_cluster_{}".format(i)])
    narrow_cluster_in_req = quad_narrow_xbar.__dict__["out_cluster_{}".format(i)].req_name()
    wide_cluster_in_req = quad_wide_xbar.__dict__["out_cluster_{}".format(i)].req_name()
  %>
  assign bingo_cluster_access[${i}] = ${narrow_cluster_in_req}.ar_valid | ${narrow_cluster_in_req}.aw_valid |
                                      ${wide_cluster_in_req}.ar_valid | ${wide_cluster_in_req}.aw_valid;
  ${cluster_name}_wrapper i_${name}_cluster_${i} (
    .clk_i               (clk_acc_i[${i}]),
    .rst_ni              (rst_acc_ni[${i}]),
    .obs_o               (/* Not Connected */),
    .meip_i              (meip_i[NrCoresPerClusterOffset[${i}]+:NrCoresPerCluster[${i}]]),
    .mtip_i              (mtip_i[NrCoresPerClusterOffset[${i}]+:NrCoresPerCluster[${i}]]),
    .msip_i              (msip_i[NrCoresPerClusterOffset[${i}]+:NrCoresPerCluster[${i}]]),
    .hart_base_id_i      (hart_base_id_${i}),
    .cluster_base_addr_i (cluster_base_addr[${i}]),
    .boot_addr_i         (boot_addr_i),
    // CSR Req/Rsp to HW Scheduler
    .csr_req_o           (csr_req_${i}       ),
    .csr_req_valid_o     (csr_req_valid_${i} ),
    .csr_req_ready_i     (csr_req_ready_${i} ),
    .csr_resp_i          (csr_rsp_cdc_${i}      ),
    .csr_resp_valid_i    (csr_rsp_cdc_valid_${i}),
    .csr_resp_ready_o    (csr_rsp_cdc_ready_${i}),
    // AXI Interconnect
    .narrow_in_req_i     (${narrow_cluster_in.req_name()}),
    .narrow_in_resp_o    (${narrow_cluster_in.rsp_name()}),
    .narrow_out_req_o    (${narrow_cluster_out.req_name()}),
    .narrow_out_resp_i   (${narrow_cluster_out.rsp_name()}),
    .wide_out_req_o      (${wide_cluster_out.req_name()}),
    .wide_out_resp_i     (${wide_cluster_out.rsp_name()}),
    .wide_in_req_i       (${wide_cluster_in.req_name()}),
    .wide_in_resp_o      (${wide_cluster_in.rsp_name()}),
    .sram_cfgs_i         (sram_cfg_i.cluster)
  );
  %endif
% endfor

// CDC for the CSR Req/Rsp
% for i in range(nr_clusters):
  % for j in range(nr_cores_per_cluster):
  cdc_fifo_gray #(
    .T (csr_req_t),
    .LOG_DEPTH  (1),
    .SYNC_STAGES(2)
  ) i_csr_req_cdc_cluster${i}_core${j} (
    .src_rst_ni (rst_acc_ni[${i}]            ),
    .src_clk_i  (clk_acc_i[${i}]             ),
    .src_data_i (csr_req_${i}[${j}]          ),
    .src_valid_i(csr_req_valid_${i}[${j}]    ),
    .src_ready_o(csr_req_ready_${i}[${j}]    ),

    .dst_rst_ni (rst_ni                      ),
    .dst_clk_i  (clk_i                       ),
    .dst_data_o (csr_req_cdc_${i}[${j}]      ),
    .dst_valid_o(csr_req_cdc_valid_${i}[${j}]),
    .dst_ready_i(csr_req_cdc_ready_${i}[${j}])
  );

  cdc_fifo_gray #(
    .T (csr_rsp_t),
    .LOG_DEPTH  (1),
    .SYNC_STAGES(2)
  ) i_csr_rsp_cdc_cluster${i}_core${j} (
    .src_rst_ni (rst_ni                      ),
    .src_clk_i  (clk_i                       ),
    .src_data_i (csr_rsp_${i}[${j}]          ),
    .src_valid_i(csr_rsp_valid_${i}[${j}]    ),
    .src_ready_o(csr_rsp_ready_${i}[${j}]    ),

    .dst_rst_ni (rst_acc_ni[${i}]            ),
    .dst_clk_i  (clk_acc_i[${i}]             ),
    .dst_data_o (csr_rsp_cdc_${i}[${j}]      ),
    .dst_valid_o(csr_rsp_cdc_valid_${i}[${j}]),
    .dst_ready_i(csr_rsp_cdc_ready_${i}[${j}])
  );
  %endfor
% endfor



endmodule
